// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FONTBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_FONTBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace asdx {
namespace res {

struct Bounds;

struct Glyph;

struct FontBinary;
struct FontBinaryBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Bounds FLATBUFFERS_FINAL_CLASS {
 private:
  float Left_;
  float Right_;
  float Top_;
  float Bottom_;

 public:
  Bounds()
      : Left_(0),
        Right_(0),
        Top_(0),
        Bottom_(0) {
  }
  Bounds(float _Left, float _Right, float _Top, float _Bottom)
      : Left_(::flatbuffers::EndianScalar(_Left)),
        Right_(::flatbuffers::EndianScalar(_Right)),
        Top_(::flatbuffers::EndianScalar(_Top)),
        Bottom_(::flatbuffers::EndianScalar(_Bottom)) {
  }
  float Left() const {
    return ::flatbuffers::EndianScalar(Left_);
  }
  float Right() const {
    return ::flatbuffers::EndianScalar(Right_);
  }
  float Top() const {
    return ::flatbuffers::EndianScalar(Top_);
  }
  float Bottom() const {
    return ::flatbuffers::EndianScalar(Bottom_);
  }
};
FLATBUFFERS_STRUCT_END(Bounds, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Glyph FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t Unicode_;
  float Advance_;
  asdx::res::Bounds AtlasBound_;
  asdx::res::Bounds PlaneBound_;

 public:
  Glyph()
      : Unicode_(0),
        Advance_(0),
        AtlasBound_(),
        PlaneBound_() {
  }
  Glyph(uint32_t _Unicode, float _Advance, const asdx::res::Bounds &_AtlasBound, const asdx::res::Bounds &_PlaneBound)
      : Unicode_(::flatbuffers::EndianScalar(_Unicode)),
        Advance_(::flatbuffers::EndianScalar(_Advance)),
        AtlasBound_(_AtlasBound),
        PlaneBound_(_PlaneBound) {
  }
  uint32_t Unicode() const {
    return ::flatbuffers::EndianScalar(Unicode_);
  }
  bool KeyCompareLessThan(const Glyph * const o) const {
    return Unicode() < o->Unicode();
  }
  int KeyCompareWithValue(uint32_t _Unicode) const {
    return static_cast<int>(Unicode() > _Unicode) - static_cast<int>(Unicode() < _Unicode);
  }
  float Advance() const {
    return ::flatbuffers::EndianScalar(Advance_);
  }
  const asdx::res::Bounds &AtlasBound() const {
    return AtlasBound_;
  }
  const asdx::res::Bounds &PlaneBound() const {
    return PlaneBound_;
  }
};
FLATBUFFERS_STRUCT_END(Glyph, 40);

struct FontBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FontBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_DISTANCERANGE = 6,
    VT_FONTSIZE = 8,
    VT_TEXTUREWIDTH = 10,
    VT_TEXTUREHEIGHT = 12,
    VT_EMSIZE = 14,
    VT_LINEHEIGHT = 16,
    VT_ASCENDER = 18,
    VT_DESCENDER = 20,
    VT_FLIPY = 22,
    VT_TEXTUREFORMAT = 24,
    VT_GLYPHS = 26,
    VT_TEXELS = 28
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  float DistanceRange() const {
    return GetField<float>(VT_DISTANCERANGE, 0.0f);
  }
  uint32_t FontSize() const {
    return GetField<uint32_t>(VT_FONTSIZE, 0);
  }
  uint32_t TextureWidth() const {
    return GetField<uint32_t>(VT_TEXTUREWIDTH, 0);
  }
  uint32_t TextureHeight() const {
    return GetField<uint32_t>(VT_TEXTUREHEIGHT, 0);
  }
  float EmSize() const {
    return GetField<float>(VT_EMSIZE, 0.0f);
  }
  float LineHeight() const {
    return GetField<float>(VT_LINEHEIGHT, 0.0f);
  }
  float Ascender() const {
    return GetField<float>(VT_ASCENDER, 0.0f);
  }
  float Descender() const {
    return GetField<float>(VT_DESCENDER, 0.0f);
  }
  bool FlipY() const {
    return GetField<uint8_t>(VT_FLIPY, 0) != 0;
  }
  uint32_t TextureFormat() const {
    return GetField<uint32_t>(VT_TEXTUREFORMAT, 0);
  }
  const ::flatbuffers::Vector<const asdx::res::Glyph *> *Glyphs() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Glyph *> *>(VT_GLYPHS);
  }
  const ::flatbuffers::Vector<uint8_t> *Texels() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_TEXELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<float>(verifier, VT_DISTANCERANGE, 4) &&
           VerifyField<uint32_t>(verifier, VT_FONTSIZE, 4) &&
           VerifyField<uint32_t>(verifier, VT_TEXTUREWIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_TEXTUREHEIGHT, 4) &&
           VerifyField<float>(verifier, VT_EMSIZE, 4) &&
           VerifyField<float>(verifier, VT_LINEHEIGHT, 4) &&
           VerifyField<float>(verifier, VT_ASCENDER, 4) &&
           VerifyField<float>(verifier, VT_DESCENDER, 4) &&
           VerifyField<uint8_t>(verifier, VT_FLIPY, 1) &&
           VerifyField<uint32_t>(verifier, VT_TEXTUREFORMAT, 4) &&
           VerifyOffset(verifier, VT_GLYPHS) &&
           verifier.VerifyVector(Glyphs()) &&
           VerifyOffset(verifier, VT_TEXELS) &&
           verifier.VerifyVector(Texels()) &&
           verifier.EndTable();
  }
};

struct FontBinaryBuilder {
  typedef FontBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(FontBinary::VT_VERSION, Version, 0);
  }
  void add_DistanceRange(float DistanceRange) {
    fbb_.AddElement<float>(FontBinary::VT_DISTANCERANGE, DistanceRange, 0.0f);
  }
  void add_FontSize(uint32_t FontSize) {
    fbb_.AddElement<uint32_t>(FontBinary::VT_FONTSIZE, FontSize, 0);
  }
  void add_TextureWidth(uint32_t TextureWidth) {
    fbb_.AddElement<uint32_t>(FontBinary::VT_TEXTUREWIDTH, TextureWidth, 0);
  }
  void add_TextureHeight(uint32_t TextureHeight) {
    fbb_.AddElement<uint32_t>(FontBinary::VT_TEXTUREHEIGHT, TextureHeight, 0);
  }
  void add_EmSize(float EmSize) {
    fbb_.AddElement<float>(FontBinary::VT_EMSIZE, EmSize, 0.0f);
  }
  void add_LineHeight(float LineHeight) {
    fbb_.AddElement<float>(FontBinary::VT_LINEHEIGHT, LineHeight, 0.0f);
  }
  void add_Ascender(float Ascender) {
    fbb_.AddElement<float>(FontBinary::VT_ASCENDER, Ascender, 0.0f);
  }
  void add_Descender(float Descender) {
    fbb_.AddElement<float>(FontBinary::VT_DESCENDER, Descender, 0.0f);
  }
  void add_FlipY(bool FlipY) {
    fbb_.AddElement<uint8_t>(FontBinary::VT_FLIPY, static_cast<uint8_t>(FlipY), 0);
  }
  void add_TextureFormat(uint32_t TextureFormat) {
    fbb_.AddElement<uint32_t>(FontBinary::VT_TEXTUREFORMAT, TextureFormat, 0);
  }
  void add_Glyphs(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Glyph *>> Glyphs) {
    fbb_.AddOffset(FontBinary::VT_GLYPHS, Glyphs);
  }
  void add_Texels(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Texels) {
    fbb_.AddOffset(FontBinary::VT_TEXELS, Texels);
  }
  explicit FontBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FontBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FontBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FontBinary> CreateFontBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    float DistanceRange = 0.0f,
    uint32_t FontSize = 0,
    uint32_t TextureWidth = 0,
    uint32_t TextureHeight = 0,
    float EmSize = 0.0f,
    float LineHeight = 0.0f,
    float Ascender = 0.0f,
    float Descender = 0.0f,
    bool FlipY = false,
    uint32_t TextureFormat = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Glyph *>> Glyphs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Texels = 0) {
  FontBinaryBuilder builder_(_fbb);
  builder_.add_Texels(Texels);
  builder_.add_Glyphs(Glyphs);
  builder_.add_TextureFormat(TextureFormat);
  builder_.add_Descender(Descender);
  builder_.add_Ascender(Ascender);
  builder_.add_LineHeight(LineHeight);
  builder_.add_EmSize(EmSize);
  builder_.add_TextureHeight(TextureHeight);
  builder_.add_TextureWidth(TextureWidth);
  builder_.add_FontSize(FontSize);
  builder_.add_DistanceRange(DistanceRange);
  builder_.add_Version(Version);
  builder_.add_FlipY(FlipY);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FontBinary> CreateFontBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    float DistanceRange = 0.0f,
    uint32_t FontSize = 0,
    uint32_t TextureWidth = 0,
    uint32_t TextureHeight = 0,
    float EmSize = 0.0f,
    float LineHeight = 0.0f,
    float Ascender = 0.0f,
    float Descender = 0.0f,
    bool FlipY = false,
    uint32_t TextureFormat = 0,
    std::vector<asdx::res::Glyph> *Glyphs = nullptr,
    const std::vector<uint8_t> *Texels = nullptr) {
  auto Glyphs__ = Glyphs ? _fbb.CreateVectorOfSortedStructs<asdx::res::Glyph>(Glyphs) : 0;
  auto Texels__ = Texels ? _fbb.CreateVector<uint8_t>(*Texels) : 0;
  return asdx::res::CreateFontBinary(
      _fbb,
      Version,
      DistanceRange,
      FontSize,
      TextureWidth,
      TextureHeight,
      EmSize,
      LineHeight,
      Ascender,
      Descender,
      FlipY,
      TextureFormat,
      Glyphs__,
      Texels__);
}

inline const asdx::res::FontBinary *GetFontBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::FontBinary>(buf);
}

inline const asdx::res::FontBinary *GetSizePrefixedFontBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::FontBinary>(buf);
}

inline bool VerifyFontBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::FontBinary>(nullptr);
}

inline bool VerifySizePrefixedFontBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::FontBinary>(nullptr);
}

inline void FinishFontBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::FontBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFontBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::FontBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_FONTBINARY_ASDX_RES_H_
