// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAPCHIPBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_MAPCHIPBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "ResTypes_generated.h"

namespace asdx {
namespace res {

struct MapTileProp;

struct MapChipFrame;

struct MapChip;
struct MapChipBuilder;

struct MapLayer;
struct MapLayerBuilder;

struct MapChipBinary;
struct MapChipBinaryBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) MapTileProp FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t Flags_;
  uint16_t EventId_;

 public:
  MapTileProp()
      : Flags_(0),
        EventId_(0) {
  }
  MapTileProp(uint16_t _Flags, uint16_t _EventId)
      : Flags_(::flatbuffers::EndianScalar(_Flags)),
        EventId_(::flatbuffers::EndianScalar(_EventId)) {
  }
  uint16_t Flags() const {
    return ::flatbuffers::EndianScalar(Flags_);
  }
  uint16_t EventId() const {
    return ::flatbuffers::EndianScalar(EventId_);
  }
};
FLATBUFFERS_STRUCT_END(MapTileProp, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) MapChipFrame FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t Id_;
  float Duration_;

 public:
  MapChipFrame()
      : Id_(0),
        Duration_(0) {
  }
  MapChipFrame(uint32_t _Id, float _Duration)
      : Id_(::flatbuffers::EndianScalar(_Id)),
        Duration_(::flatbuffers::EndianScalar(_Duration)) {
  }
  uint32_t Id() const {
    return ::flatbuffers::EndianScalar(Id_);
  }
  float Duration() const {
    return ::flatbuffers::EndianScalar(Duration_);
  }
};
FLATBUFFERS_STRUCT_END(MapChipFrame, 8);

struct MapChip FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapChipBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_FRAMES = 6
  };
  uint16_t Id() const {
    return GetField<uint16_t>(VT_ID, 0);
  }
  const ::flatbuffers::Vector<const asdx::res::MapChipFrame *> *Frames() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::MapChipFrame *> *>(VT_FRAMES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_ID, 2) &&
           VerifyOffset(verifier, VT_FRAMES) &&
           verifier.VerifyVector(Frames()) &&
           verifier.EndTable();
  }
};

struct MapChipBuilder {
  typedef MapChip Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Id(uint16_t Id) {
    fbb_.AddElement<uint16_t>(MapChip::VT_ID, Id, 0);
  }
  void add_Frames(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::MapChipFrame *>> Frames) {
    fbb_.AddOffset(MapChip::VT_FRAMES, Frames);
  }
  explicit MapChipBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapChip> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapChip>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapChip> CreateMapChip(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t Id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::MapChipFrame *>> Frames = 0) {
  MapChipBuilder builder_(_fbb);
  builder_.add_Frames(Frames);
  builder_.add_Id(Id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MapChip> CreateMapChipDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t Id = 0,
    const std::vector<asdx::res::MapChipFrame> *Frames = nullptr) {
  auto Frames__ = Frames ? _fbb.CreateVectorOfStructs<asdx::res::MapChipFrame>(*Frames) : 0;
  return asdx::res::CreateMapChip(
      _fbb,
      Id,
      Frames__);
}

struct MapLayer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapLayerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_CHIPS = 6
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<uint16_t> *Chips() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_CHIPS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyOffset(verifier, VT_CHIPS) &&
           verifier.VerifyVector(Chips()) &&
           verifier.EndTable();
  }
};

struct MapLayerBuilder {
  typedef MapLayer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(MapLayer::VT_NAME, Name);
  }
  void add_Chips(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> Chips) {
    fbb_.AddOffset(MapLayer::VT_CHIPS, Chips);
  }
  explicit MapLayerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapLayer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapLayer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapLayer> CreateMapLayer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> Chips = 0) {
  MapLayerBuilder builder_(_fbb);
  builder_.add_Chips(Chips);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MapLayer> CreateMapLayerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    const std::vector<uint16_t> *Chips = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Chips__ = Chips ? _fbb.CreateVector<uint16_t>(*Chips) : 0;
  return asdx::res::CreateMapLayer(
      _fbb,
      Name__,
      Chips__);
}

struct MapChipBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapChipBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_MAPCOUNT = 6,
    VT_CHIPCOUNT = 8,
    VT_CHIPSIZE = 10,
    VT_TEXTURESIZE = 12,
    VT_TEXTUREPATH = 14,
    VT_FIRSTCHIPID = 16,
    VT_LAYERS = 18,
    VT_TILEPROPS = 20,
    VT_CHIPS = 22
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const asdx::res::Uint2 *MapCount() const {
    return GetStruct<const asdx::res::Uint2 *>(VT_MAPCOUNT);
  }
  const asdx::res::Uint2 *ChipCount() const {
    return GetStruct<const asdx::res::Uint2 *>(VT_CHIPCOUNT);
  }
  const asdx::res::Uint2 *ChipSize() const {
    return GetStruct<const asdx::res::Uint2 *>(VT_CHIPSIZE);
  }
  const asdx::res::Uint2 *TextureSize() const {
    return GetStruct<const asdx::res::Uint2 *>(VT_TEXTURESIZE);
  }
  const ::flatbuffers::String *TexturePath() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXTUREPATH);
  }
  uint16_t FirstChipId() const {
    return GetField<uint16_t>(VT_FIRSTCHIPID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MapLayer>> *Layers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MapLayer>> *>(VT_LAYERS);
  }
  const ::flatbuffers::Vector<const asdx::res::MapTileProp *> *TileProps() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::MapTileProp *> *>(VT_TILEPROPS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MapChip>> *Chips() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MapChip>> *>(VT_CHIPS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<asdx::res::Uint2>(verifier, VT_MAPCOUNT, 4) &&
           VerifyField<asdx::res::Uint2>(verifier, VT_CHIPCOUNT, 4) &&
           VerifyField<asdx::res::Uint2>(verifier, VT_CHIPSIZE, 4) &&
           VerifyField<asdx::res::Uint2>(verifier, VT_TEXTURESIZE, 4) &&
           VerifyOffset(verifier, VT_TEXTUREPATH) &&
           verifier.VerifyString(TexturePath()) &&
           VerifyField<uint16_t>(verifier, VT_FIRSTCHIPID, 2) &&
           VerifyOffset(verifier, VT_LAYERS) &&
           verifier.VerifyVector(Layers()) &&
           verifier.VerifyVectorOfTables(Layers()) &&
           VerifyOffset(verifier, VT_TILEPROPS) &&
           verifier.VerifyVector(TileProps()) &&
           VerifyOffset(verifier, VT_CHIPS) &&
           verifier.VerifyVector(Chips()) &&
           verifier.VerifyVectorOfTables(Chips()) &&
           verifier.EndTable();
  }
};

struct MapChipBinaryBuilder {
  typedef MapChipBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(MapChipBinary::VT_VERSION, Version, 0);
  }
  void add_MapCount(const asdx::res::Uint2 *MapCount) {
    fbb_.AddStruct(MapChipBinary::VT_MAPCOUNT, MapCount);
  }
  void add_ChipCount(const asdx::res::Uint2 *ChipCount) {
    fbb_.AddStruct(MapChipBinary::VT_CHIPCOUNT, ChipCount);
  }
  void add_ChipSize(const asdx::res::Uint2 *ChipSize) {
    fbb_.AddStruct(MapChipBinary::VT_CHIPSIZE, ChipSize);
  }
  void add_TextureSize(const asdx::res::Uint2 *TextureSize) {
    fbb_.AddStruct(MapChipBinary::VT_TEXTURESIZE, TextureSize);
  }
  void add_TexturePath(::flatbuffers::Offset<::flatbuffers::String> TexturePath) {
    fbb_.AddOffset(MapChipBinary::VT_TEXTUREPATH, TexturePath);
  }
  void add_FirstChipId(uint16_t FirstChipId) {
    fbb_.AddElement<uint16_t>(MapChipBinary::VT_FIRSTCHIPID, FirstChipId, 0);
  }
  void add_Layers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MapLayer>>> Layers) {
    fbb_.AddOffset(MapChipBinary::VT_LAYERS, Layers);
  }
  void add_TileProps(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::MapTileProp *>> TileProps) {
    fbb_.AddOffset(MapChipBinary::VT_TILEPROPS, TileProps);
  }
  void add_Chips(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MapChip>>> Chips) {
    fbb_.AddOffset(MapChipBinary::VT_CHIPS, Chips);
  }
  explicit MapChipBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapChipBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapChipBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapChipBinary> CreateMapChipBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    const asdx::res::Uint2 *MapCount = nullptr,
    const asdx::res::Uint2 *ChipCount = nullptr,
    const asdx::res::Uint2 *ChipSize = nullptr,
    const asdx::res::Uint2 *TextureSize = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> TexturePath = 0,
    uint16_t FirstChipId = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MapLayer>>> Layers = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::MapTileProp *>> TileProps = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MapChip>>> Chips = 0) {
  MapChipBinaryBuilder builder_(_fbb);
  builder_.add_Chips(Chips);
  builder_.add_TileProps(TileProps);
  builder_.add_Layers(Layers);
  builder_.add_TexturePath(TexturePath);
  builder_.add_TextureSize(TextureSize);
  builder_.add_ChipSize(ChipSize);
  builder_.add_ChipCount(ChipCount);
  builder_.add_MapCount(MapCount);
  builder_.add_Version(Version);
  builder_.add_FirstChipId(FirstChipId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MapChipBinary> CreateMapChipBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    const asdx::res::Uint2 *MapCount = nullptr,
    const asdx::res::Uint2 *ChipCount = nullptr,
    const asdx::res::Uint2 *ChipSize = nullptr,
    const asdx::res::Uint2 *TextureSize = nullptr,
    const char *TexturePath = nullptr,
    uint16_t FirstChipId = 0,
    const std::vector<::flatbuffers::Offset<asdx::res::MapLayer>> *Layers = nullptr,
    const std::vector<asdx::res::MapTileProp> *TileProps = nullptr,
    const std::vector<::flatbuffers::Offset<asdx::res::MapChip>> *Chips = nullptr) {
  auto TexturePath__ = TexturePath ? _fbb.CreateString(TexturePath) : 0;
  auto Layers__ = Layers ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::MapLayer>>(*Layers) : 0;
  auto TileProps__ = TileProps ? _fbb.CreateVectorOfStructs<asdx::res::MapTileProp>(*TileProps) : 0;
  auto Chips__ = Chips ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::MapChip>>(*Chips) : 0;
  return asdx::res::CreateMapChipBinary(
      _fbb,
      Version,
      MapCount,
      ChipCount,
      ChipSize,
      TextureSize,
      TexturePath__,
      FirstChipId,
      Layers__,
      TileProps__,
      Chips__);
}

inline const asdx::res::MapChipBinary *GetMapChipBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::MapChipBinary>(buf);
}

inline const asdx::res::MapChipBinary *GetSizePrefixedMapChipBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::MapChipBinary>(buf);
}

inline bool VerifyMapChipBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::MapChipBinary>(nullptr);
}

inline bool VerifySizePrefixedMapChipBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::MapChipBinary>(nullptr);
}

inline void FinishMapChipBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MapChipBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMapChipBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MapChipBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_MAPCHIPBINARY_ASDX_RES_H_
