// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAPCHIPBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_MAPCHIPBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace asdx {
namespace res {

struct MapChipSubResource;

struct MapChip;
struct MapChipBuilder;

struct Layer;
struct LayerBuilder;

struct Tile;

struct TileSet;
struct TileSetBuilder;

struct MapChipBinary;
struct MapChipBinaryBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) MapChipSubResource FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t Width_;
  uint32_t Height_;
  uint64_t RowPitch_;
  uint64_t SlicePitch_;
  uint64_t PixelOffset_;

 public:
  MapChipSubResource()
      : Width_(0),
        Height_(0),
        RowPitch_(0),
        SlicePitch_(0),
        PixelOffset_(0) {
  }
  MapChipSubResource(uint32_t _Width, uint32_t _Height, uint64_t _RowPitch, uint64_t _SlicePitch, uint64_t _PixelOffset)
      : Width_(::flatbuffers::EndianScalar(_Width)),
        Height_(::flatbuffers::EndianScalar(_Height)),
        RowPitch_(::flatbuffers::EndianScalar(_RowPitch)),
        SlicePitch_(::flatbuffers::EndianScalar(_SlicePitch)),
        PixelOffset_(::flatbuffers::EndianScalar(_PixelOffset)) {
  }
  uint32_t Width() const {
    return ::flatbuffers::EndianScalar(Width_);
  }
  uint32_t Height() const {
    return ::flatbuffers::EndianScalar(Height_);
  }
  uint64_t RowPitch() const {
    return ::flatbuffers::EndianScalar(RowPitch_);
  }
  uint64_t SlicePitch() const {
    return ::flatbuffers::EndianScalar(SlicePitch_);
  }
  uint64_t PixelOffset() const {
    return ::flatbuffers::EndianScalar(PixelOffset_);
  }
};
FLATBUFFERS_STRUCT_END(MapChipSubResource, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Tile FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t Id_;
  uint8_t Collision_;
  int8_t padding0__;
  uint32_t Event_;

 public:
  Tile()
      : Id_(0),
        Collision_(0),
        padding0__(0),
        Event_(0) {
    (void)padding0__;
  }
  Tile(uint16_t _Id, bool _Collision, uint32_t _Event)
      : Id_(::flatbuffers::EndianScalar(_Id)),
        Collision_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_Collision))),
        padding0__(0),
        Event_(::flatbuffers::EndianScalar(_Event)) {
    (void)padding0__;
  }
  uint16_t Id() const {
    return ::flatbuffers::EndianScalar(Id_);
  }
  bool KeyCompareLessThan(const Tile * const o) const {
    return Id() < o->Id();
  }
  int KeyCompareWithValue(uint16_t _Id) const {
    return static_cast<int>(Id() > _Id) - static_cast<int>(Id() < _Id);
  }
  bool Collision() const {
    return ::flatbuffers::EndianScalar(Collision_) != 0;
  }
  uint32_t Event() const {
    return ::flatbuffers::EndianScalar(Event_);
  }
};
FLATBUFFERS_STRUCT_END(Tile, 8);

struct MapChip FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapChipBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WIDTH = 4,
    VT_HEIGHT = 6,
    VT_FORMAT = 8,
    VT_SUBRESOURCES = 10,
    VT_PIXELS = 12
  };
  uint32_t Width() const {
    return GetField<uint32_t>(VT_WIDTH, 0);
  }
  uint32_t Height() const {
    return GetField<uint32_t>(VT_HEIGHT, 0);
  }
  uint32_t Format() const {
    return GetField<uint32_t>(VT_FORMAT, 0);
  }
  const ::flatbuffers::Vector<const asdx::res::MapChipSubResource *> *SubResources() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::MapChipSubResource *> *>(VT_SUBRESOURCES);
  }
  const ::flatbuffers::Vector<uint8_t> *Pixels() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PIXELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyField<uint32_t>(verifier, VT_FORMAT, 4) &&
           VerifyOffset(verifier, VT_SUBRESOURCES) &&
           verifier.VerifyVector(SubResources()) &&
           VerifyOffset(verifier, VT_PIXELS) &&
           verifier.VerifyVector(Pixels()) &&
           verifier.EndTable();
  }
};

struct MapChipBuilder {
  typedef MapChip Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Width(uint32_t Width) {
    fbb_.AddElement<uint32_t>(MapChip::VT_WIDTH, Width, 0);
  }
  void add_Height(uint32_t Height) {
    fbb_.AddElement<uint32_t>(MapChip::VT_HEIGHT, Height, 0);
  }
  void add_Format(uint32_t Format) {
    fbb_.AddElement<uint32_t>(MapChip::VT_FORMAT, Format, 0);
  }
  void add_SubResources(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::MapChipSubResource *>> SubResources) {
    fbb_.AddOffset(MapChip::VT_SUBRESOURCES, SubResources);
  }
  void add_Pixels(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Pixels) {
    fbb_.AddOffset(MapChip::VT_PIXELS, Pixels);
  }
  explicit MapChipBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapChip> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapChip>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapChip> CreateMapChip(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Width = 0,
    uint32_t Height = 0,
    uint32_t Format = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::MapChipSubResource *>> SubResources = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Pixels = 0) {
  MapChipBuilder builder_(_fbb);
  builder_.add_Pixels(Pixels);
  builder_.add_SubResources(SubResources);
  builder_.add_Format(Format);
  builder_.add_Height(Height);
  builder_.add_Width(Width);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MapChip> CreateMapChipDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Width = 0,
    uint32_t Height = 0,
    uint32_t Format = 0,
    const std::vector<asdx::res::MapChipSubResource> *SubResources = nullptr,
    const std::vector<uint8_t> *Pixels = nullptr) {
  auto SubResources__ = SubResources ? _fbb.CreateVectorOfStructs<asdx::res::MapChipSubResource>(*SubResources) : 0;
  auto Pixels__ = Pixels ? _fbb.CreateVector<uint8_t>(*Pixels) : 0;
  return asdx::res::CreateMapChip(
      _fbb,
      Width,
      Height,
      Format,
      SubResources__,
      Pixels__);
}

struct Layer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LayerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_ID = 6,
    VT_ROWS = 8,
    VT_COLUMNS = 10,
    VT_DATA = 12
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t Id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  uint32_t Rows() const {
    return GetField<uint32_t>(VT_ROWS, 0);
  }
  uint32_t Columns() const {
    return GetField<uint32_t>(VT_COLUMNS, 0);
  }
  const ::flatbuffers::Vector<uint16_t> *Data() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_ROWS, 4) &&
           VerifyField<uint32_t>(verifier, VT_COLUMNS, 4) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(Data()) &&
           verifier.EndTable();
  }
};

struct LayerBuilder {
  typedef Layer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(Layer::VT_NAME, Name);
  }
  void add_Id(uint32_t Id) {
    fbb_.AddElement<uint32_t>(Layer::VT_ID, Id, 0);
  }
  void add_Rows(uint32_t Rows) {
    fbb_.AddElement<uint32_t>(Layer::VT_ROWS, Rows, 0);
  }
  void add_Columns(uint32_t Columns) {
    fbb_.AddElement<uint32_t>(Layer::VT_COLUMNS, Columns, 0);
  }
  void add_Data(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> Data) {
    fbb_.AddOffset(Layer::VT_DATA, Data);
  }
  explicit LayerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Layer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Layer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Layer> CreateLayer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    uint32_t Id = 0,
    uint32_t Rows = 0,
    uint32_t Columns = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> Data = 0) {
  LayerBuilder builder_(_fbb);
  builder_.add_Data(Data);
  builder_.add_Columns(Columns);
  builder_.add_Rows(Rows);
  builder_.add_Id(Id);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Layer> CreateLayerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    uint32_t Id = 0,
    uint32_t Rows = 0,
    uint32_t Columns = 0,
    const std::vector<uint16_t> *Data = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Data__ = Data ? _fbb.CreateVector<uint16_t>(*Data) : 0;
  return asdx::res::CreateLayer(
      _fbb,
      Name__,
      Id,
      Rows,
      Columns,
      Data__);
}

struct TileSet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TileSetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_FIRSTCHIPID = 6,
    VT_COLUMNS = 8,
    VT_TILECOUNT = 10,
    VT_TILEWIDTH = 12,
    VT_TILEHEIGHT = 14,
    VT_IMAGE = 16,
    VT_TILES = 18
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint16_t FirstChipId() const {
    return GetField<uint16_t>(VT_FIRSTCHIPID, 0);
  }
  uint32_t Columns() const {
    return GetField<uint32_t>(VT_COLUMNS, 0);
  }
  uint32_t TileCount() const {
    return GetField<uint32_t>(VT_TILECOUNT, 0);
  }
  uint32_t TileWidth() const {
    return GetField<uint32_t>(VT_TILEWIDTH, 0);
  }
  uint32_t TileHeight() const {
    return GetField<uint32_t>(VT_TILEHEIGHT, 0);
  }
  const asdx::res::MapChip *Image() const {
    return GetPointer<const asdx::res::MapChip *>(VT_IMAGE);
  }
  const ::flatbuffers::Vector<const asdx::res::Tile *> *Tiles() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Tile *> *>(VT_TILES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyField<uint16_t>(verifier, VT_FIRSTCHIPID, 2) &&
           VerifyField<uint32_t>(verifier, VT_COLUMNS, 4) &&
           VerifyField<uint32_t>(verifier, VT_TILECOUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_TILEWIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_TILEHEIGHT, 4) &&
           VerifyOffset(verifier, VT_IMAGE) &&
           verifier.VerifyTable(Image()) &&
           VerifyOffset(verifier, VT_TILES) &&
           verifier.VerifyVector(Tiles()) &&
           verifier.EndTable();
  }
};

struct TileSetBuilder {
  typedef TileSet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(TileSet::VT_NAME, Name);
  }
  void add_FirstChipId(uint16_t FirstChipId) {
    fbb_.AddElement<uint16_t>(TileSet::VT_FIRSTCHIPID, FirstChipId, 0);
  }
  void add_Columns(uint32_t Columns) {
    fbb_.AddElement<uint32_t>(TileSet::VT_COLUMNS, Columns, 0);
  }
  void add_TileCount(uint32_t TileCount) {
    fbb_.AddElement<uint32_t>(TileSet::VT_TILECOUNT, TileCount, 0);
  }
  void add_TileWidth(uint32_t TileWidth) {
    fbb_.AddElement<uint32_t>(TileSet::VT_TILEWIDTH, TileWidth, 0);
  }
  void add_TileHeight(uint32_t TileHeight) {
    fbb_.AddElement<uint32_t>(TileSet::VT_TILEHEIGHT, TileHeight, 0);
  }
  void add_Image(::flatbuffers::Offset<asdx::res::MapChip> Image) {
    fbb_.AddOffset(TileSet::VT_IMAGE, Image);
  }
  void add_Tiles(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Tile *>> Tiles) {
    fbb_.AddOffset(TileSet::VT_TILES, Tiles);
  }
  explicit TileSetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TileSet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TileSet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TileSet> CreateTileSet(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    uint16_t FirstChipId = 0,
    uint32_t Columns = 0,
    uint32_t TileCount = 0,
    uint32_t TileWidth = 0,
    uint32_t TileHeight = 0,
    ::flatbuffers::Offset<asdx::res::MapChip> Image = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Tile *>> Tiles = 0) {
  TileSetBuilder builder_(_fbb);
  builder_.add_Tiles(Tiles);
  builder_.add_Image(Image);
  builder_.add_TileHeight(TileHeight);
  builder_.add_TileWidth(TileWidth);
  builder_.add_TileCount(TileCount);
  builder_.add_Columns(Columns);
  builder_.add_Name(Name);
  builder_.add_FirstChipId(FirstChipId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TileSet> CreateTileSetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    uint16_t FirstChipId = 0,
    uint32_t Columns = 0,
    uint32_t TileCount = 0,
    uint32_t TileWidth = 0,
    uint32_t TileHeight = 0,
    ::flatbuffers::Offset<asdx::res::MapChip> Image = 0,
    std::vector<asdx::res::Tile> *Tiles = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Tiles__ = Tiles ? _fbb.CreateVectorOfSortedStructs<asdx::res::Tile>(Tiles) : 0;
  return asdx::res::CreateTileSet(
      _fbb,
      Name__,
      FirstChipId,
      Columns,
      TileCount,
      TileWidth,
      TileHeight,
      Image,
      Tiles__);
}

struct MapChipBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapChipBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_ROWS = 6,
    VT_COLUMNS = 8,
    VT_TILEWIDTH = 10,
    VT_TILEHEIGHT = 12,
    VT_TILESETS = 14,
    VT_LAYERS = 16
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  uint32_t Rows() const {
    return GetField<uint32_t>(VT_ROWS, 0);
  }
  uint32_t Columns() const {
    return GetField<uint32_t>(VT_COLUMNS, 0);
  }
  uint32_t TileWidth() const {
    return GetField<uint32_t>(VT_TILEWIDTH, 0);
  }
  uint32_t TileHeight() const {
    return GetField<uint32_t>(VT_TILEHEIGHT, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::TileSet>> *TileSets() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::TileSet>> *>(VT_TILESETS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Layer>> *Layers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Layer>> *>(VT_LAYERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<uint32_t>(verifier, VT_ROWS, 4) &&
           VerifyField<uint32_t>(verifier, VT_COLUMNS, 4) &&
           VerifyField<uint32_t>(verifier, VT_TILEWIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_TILEHEIGHT, 4) &&
           VerifyOffset(verifier, VT_TILESETS) &&
           verifier.VerifyVector(TileSets()) &&
           verifier.VerifyVectorOfTables(TileSets()) &&
           VerifyOffset(verifier, VT_LAYERS) &&
           verifier.VerifyVector(Layers()) &&
           verifier.VerifyVectorOfTables(Layers()) &&
           verifier.EndTable();
  }
};

struct MapChipBinaryBuilder {
  typedef MapChipBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(MapChipBinary::VT_VERSION, Version, 0);
  }
  void add_Rows(uint32_t Rows) {
    fbb_.AddElement<uint32_t>(MapChipBinary::VT_ROWS, Rows, 0);
  }
  void add_Columns(uint32_t Columns) {
    fbb_.AddElement<uint32_t>(MapChipBinary::VT_COLUMNS, Columns, 0);
  }
  void add_TileWidth(uint32_t TileWidth) {
    fbb_.AddElement<uint32_t>(MapChipBinary::VT_TILEWIDTH, TileWidth, 0);
  }
  void add_TileHeight(uint32_t TileHeight) {
    fbb_.AddElement<uint32_t>(MapChipBinary::VT_TILEHEIGHT, TileHeight, 0);
  }
  void add_TileSets(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::TileSet>>> TileSets) {
    fbb_.AddOffset(MapChipBinary::VT_TILESETS, TileSets);
  }
  void add_Layers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Layer>>> Layers) {
    fbb_.AddOffset(MapChipBinary::VT_LAYERS, Layers);
  }
  explicit MapChipBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapChipBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapChipBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapChipBinary> CreateMapChipBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    uint32_t Rows = 0,
    uint32_t Columns = 0,
    uint32_t TileWidth = 0,
    uint32_t TileHeight = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::TileSet>>> TileSets = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Layer>>> Layers = 0) {
  MapChipBinaryBuilder builder_(_fbb);
  builder_.add_Layers(Layers);
  builder_.add_TileSets(TileSets);
  builder_.add_TileHeight(TileHeight);
  builder_.add_TileWidth(TileWidth);
  builder_.add_Columns(Columns);
  builder_.add_Rows(Rows);
  builder_.add_Version(Version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MapChipBinary> CreateMapChipBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    uint32_t Rows = 0,
    uint32_t Columns = 0,
    uint32_t TileWidth = 0,
    uint32_t TileHeight = 0,
    const std::vector<::flatbuffers::Offset<asdx::res::TileSet>> *TileSets = nullptr,
    const std::vector<::flatbuffers::Offset<asdx::res::Layer>> *Layers = nullptr) {
  auto TileSets__ = TileSets ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::TileSet>>(*TileSets) : 0;
  auto Layers__ = Layers ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::Layer>>(*Layers) : 0;
  return asdx::res::CreateMapChipBinary(
      _fbb,
      Version,
      Rows,
      Columns,
      TileWidth,
      TileHeight,
      TileSets__,
      Layers__);
}

inline const asdx::res::MapChipBinary *GetMapChipBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::MapChipBinary>(buf);
}

inline const asdx::res::MapChipBinary *GetSizePrefixedMapChipBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::MapChipBinary>(buf);
}

inline bool VerifyMapChipBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::MapChipBinary>(nullptr);
}

inline bool VerifySizePrefixedMapChipBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::MapChipBinary>(nullptr);
}

inline void FinishMapChipBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MapChipBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMapChipBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MapChipBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_MAPCHIPBINARY_ASDX_RES_H_
