// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MATERIALBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_MATERIALBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "ResTypes_generated.h"

namespace asdx {
namespace res {

struct MaterialTexture;
struct MaterialTextureBuilder;

struct MaterialBuffer;
struct MaterialBufferBuilder;

struct MaterialBinary;
struct MaterialBinaryBuilder;

enum MaterialBlendState : uint8_t {
  MaterialBlendState_Opaque = 0,
  MaterialBlendState_AlphaBlend = 1,
  MaterialBlendState_Additive = 2,
  MaterialBlendState_Substract = 3,
  MaterialBlendState_Premultiplied = 4,
  MaterialBlendState_Multiply = 5,
  MaterialBlendState_Screen = 6,
  MaterialBlendState_MIN = MaterialBlendState_Opaque,
  MaterialBlendState_MAX = MaterialBlendState_Screen
};

inline const MaterialBlendState (&EnumValuesMaterialBlendState())[7] {
  static const MaterialBlendState values[] = {
    MaterialBlendState_Opaque,
    MaterialBlendState_AlphaBlend,
    MaterialBlendState_Additive,
    MaterialBlendState_Substract,
    MaterialBlendState_Premultiplied,
    MaterialBlendState_Multiply,
    MaterialBlendState_Screen
  };
  return values;
}

inline const char * const *EnumNamesMaterialBlendState() {
  static const char * const names[8] = {
    "Opaque",
    "AlphaBlend",
    "Additive",
    "Substract",
    "Premultiplied",
    "Multiply",
    "Screen",
    nullptr
  };
  return names;
}

inline const char *EnumNameMaterialBlendState(MaterialBlendState e) {
  if (::flatbuffers::IsOutRange(e, MaterialBlendState_Opaque, MaterialBlendState_Screen)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMaterialBlendState()[index];
}

enum MaterialDepthState : uint8_t {
  MaterialDepthState_ReadWrite = 0,
  MaterialDepthState_ReadOnly = 1,
  MaterialDepthState_WriteOnly = 2,
  MaterialDepthState_None = 3,
  MaterialDepthState_MIN = MaterialDepthState_ReadWrite,
  MaterialDepthState_MAX = MaterialDepthState_None
};

inline const MaterialDepthState (&EnumValuesMaterialDepthState())[4] {
  static const MaterialDepthState values[] = {
    MaterialDepthState_ReadWrite,
    MaterialDepthState_ReadOnly,
    MaterialDepthState_WriteOnly,
    MaterialDepthState_None
  };
  return values;
}

inline const char * const *EnumNamesMaterialDepthState() {
  static const char * const names[5] = {
    "ReadWrite",
    "ReadOnly",
    "WriteOnly",
    "None",
    nullptr
  };
  return names;
}

inline const char *EnumNameMaterialDepthState(MaterialDepthState e) {
  if (::flatbuffers::IsOutRange(e, MaterialDepthState_ReadWrite, MaterialDepthState_None)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMaterialDepthState()[index];
}

enum MaterialRasterizerState : uint8_t {
  MaterialRasterizerState_CullNone = 0,
  MaterialRasterizerState_CullBack = 1,
  MaterialRasterizerState_CullFront = 2,
  MaterialRasterizerState_Wireframe = 3,
  MaterialRasterizerState_MIN = MaterialRasterizerState_CullNone,
  MaterialRasterizerState_MAX = MaterialRasterizerState_Wireframe
};

inline const MaterialRasterizerState (&EnumValuesMaterialRasterizerState())[4] {
  static const MaterialRasterizerState values[] = {
    MaterialRasterizerState_CullNone,
    MaterialRasterizerState_CullBack,
    MaterialRasterizerState_CullFront,
    MaterialRasterizerState_Wireframe
  };
  return values;
}

inline const char * const *EnumNamesMaterialRasterizerState() {
  static const char * const names[5] = {
    "CullNone",
    "CullBack",
    "CullFront",
    "Wireframe",
    nullptr
  };
  return names;
}

inline const char *EnumNameMaterialRasterizerState(MaterialRasterizerState e) {
  if (::flatbuffers::IsOutRange(e, MaterialRasterizerState_CullNone, MaterialRasterizerState_Wireframe)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMaterialRasterizerState()[index];
}

struct MaterialTexture FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialTextureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_PATH = 6
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *Path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(Path()) &&
           verifier.EndTable();
  }
};

struct MaterialTextureBuilder {
  typedef MaterialTexture Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(MaterialTexture::VT_NAME, Name);
  }
  void add_Path(::flatbuffers::Offset<::flatbuffers::String> Path) {
    fbb_.AddOffset(MaterialTexture::VT_PATH, Path);
  }
  explicit MaterialTextureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialTexture> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialTexture>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialTexture> CreateMaterialTexture(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> Path = 0) {
  MaterialTextureBuilder builder_(_fbb);
  builder_.add_Path(Path);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialTexture> CreateMaterialTextureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    const char *Path = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Path__ = Path ? _fbb.CreateString(Path) : 0;
  return asdx::res::CreateMaterialTexture(
      _fbb,
      Name__,
      Path__);
}

struct MaterialBuffer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBufferBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIZE = 4,
    VT_DATA = 6
  };
  uint32_t Size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *Data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(Data()) &&
           verifier.EndTable();
  }
};

struct MaterialBufferBuilder {
  typedef MaterialBuffer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Size(uint32_t Size) {
    fbb_.AddElement<uint32_t>(MaterialBuffer::VT_SIZE, Size, 0);
  }
  void add_Data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Data) {
    fbb_.AddOffset(MaterialBuffer::VT_DATA, Data);
  }
  explicit MaterialBufferBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialBuffer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialBuffer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialBuffer> CreateMaterialBuffer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Size = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Data = 0) {
  MaterialBufferBuilder builder_(_fbb);
  builder_.add_Data(Data);
  builder_.add_Size(Size);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialBuffer> CreateMaterialBufferDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Size = 0,
    const std::vector<uint8_t> *Data = nullptr) {
  auto Data__ = Data ? _fbb.CreateVector<uint8_t>(*Data) : 0;
  return asdx::res::CreateMaterialBuffer(
      _fbb,
      Size,
      Data__);
}

struct MaterialBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_KIND = 6,
    VT_BLENDSTATE = 8,
    VT_DEPTHSTATE = 10,
    VT_RASTERIZERSTATE = 12,
    VT_BUFFER = 14,
    VT_TEXTURES = 16
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  uint32_t Kind() const {
    return GetField<uint32_t>(VT_KIND, 0);
  }
  asdx::res::MaterialBlendState BlendState() const {
    return static_cast<asdx::res::MaterialBlendState>(GetField<uint8_t>(VT_BLENDSTATE, 0));
  }
  asdx::res::MaterialDepthState DepthState() const {
    return static_cast<asdx::res::MaterialDepthState>(GetField<uint8_t>(VT_DEPTHSTATE, 0));
  }
  asdx::res::MaterialRasterizerState RasterizerState() const {
    return static_cast<asdx::res::MaterialRasterizerState>(GetField<uint8_t>(VT_RASTERIZERSTATE, 0));
  }
  const asdx::res::MaterialBuffer *Buffer() const {
    return GetPointer<const asdx::res::MaterialBuffer *>(VT_BUFFER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialTexture>> *Textures() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialTexture>> *>(VT_TEXTURES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<uint32_t>(verifier, VT_KIND, 4) &&
           VerifyField<uint8_t>(verifier, VT_BLENDSTATE, 1) &&
           VerifyField<uint8_t>(verifier, VT_DEPTHSTATE, 1) &&
           VerifyField<uint8_t>(verifier, VT_RASTERIZERSTATE, 1) &&
           VerifyOffset(verifier, VT_BUFFER) &&
           verifier.VerifyTable(Buffer()) &&
           VerifyOffset(verifier, VT_TEXTURES) &&
           verifier.VerifyVector(Textures()) &&
           verifier.VerifyVectorOfTables(Textures()) &&
           verifier.EndTable();
  }
};

struct MaterialBinaryBuilder {
  typedef MaterialBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(MaterialBinary::VT_VERSION, Version, 0);
  }
  void add_Kind(uint32_t Kind) {
    fbb_.AddElement<uint32_t>(MaterialBinary::VT_KIND, Kind, 0);
  }
  void add_BlendState(asdx::res::MaterialBlendState BlendState) {
    fbb_.AddElement<uint8_t>(MaterialBinary::VT_BLENDSTATE, static_cast<uint8_t>(BlendState), 0);
  }
  void add_DepthState(asdx::res::MaterialDepthState DepthState) {
    fbb_.AddElement<uint8_t>(MaterialBinary::VT_DEPTHSTATE, static_cast<uint8_t>(DepthState), 0);
  }
  void add_RasterizerState(asdx::res::MaterialRasterizerState RasterizerState) {
    fbb_.AddElement<uint8_t>(MaterialBinary::VT_RASTERIZERSTATE, static_cast<uint8_t>(RasterizerState), 0);
  }
  void add_Buffer(::flatbuffers::Offset<asdx::res::MaterialBuffer> Buffer) {
    fbb_.AddOffset(MaterialBinary::VT_BUFFER, Buffer);
  }
  void add_Textures(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialTexture>>> Textures) {
    fbb_.AddOffset(MaterialBinary::VT_TEXTURES, Textures);
  }
  explicit MaterialBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialBinary> CreateMaterialBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    uint32_t Kind = 0,
    asdx::res::MaterialBlendState BlendState = asdx::res::MaterialBlendState_Opaque,
    asdx::res::MaterialDepthState DepthState = asdx::res::MaterialDepthState_ReadWrite,
    asdx::res::MaterialRasterizerState RasterizerState = asdx::res::MaterialRasterizerState_CullNone,
    ::flatbuffers::Offset<asdx::res::MaterialBuffer> Buffer = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialTexture>>> Textures = 0) {
  MaterialBinaryBuilder builder_(_fbb);
  builder_.add_Textures(Textures);
  builder_.add_Buffer(Buffer);
  builder_.add_Kind(Kind);
  builder_.add_Version(Version);
  builder_.add_RasterizerState(RasterizerState);
  builder_.add_DepthState(DepthState);
  builder_.add_BlendState(BlendState);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialBinary> CreateMaterialBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    uint32_t Kind = 0,
    asdx::res::MaterialBlendState BlendState = asdx::res::MaterialBlendState_Opaque,
    asdx::res::MaterialDepthState DepthState = asdx::res::MaterialDepthState_ReadWrite,
    asdx::res::MaterialRasterizerState RasterizerState = asdx::res::MaterialRasterizerState_CullNone,
    ::flatbuffers::Offset<asdx::res::MaterialBuffer> Buffer = 0,
    const std::vector<::flatbuffers::Offset<asdx::res::MaterialTexture>> *Textures = nullptr) {
  auto Textures__ = Textures ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::MaterialTexture>>(*Textures) : 0;
  return asdx::res::CreateMaterialBinary(
      _fbb,
      Version,
      Kind,
      BlendState,
      DepthState,
      RasterizerState,
      Buffer,
      Textures__);
}

inline const asdx::res::MaterialBinary *GetMaterialBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::MaterialBinary>(buf);
}

inline const asdx::res::MaterialBinary *GetSizePrefixedMaterialBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::MaterialBinary>(buf);
}

inline bool VerifyMaterialBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::MaterialBinary>(nullptr);
}

inline bool VerifySizePrefixedMaterialBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::MaterialBinary>(nullptr);
}

inline void FinishMaterialBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MaterialBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMaterialBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MaterialBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_MATERIALBINARY_ASDX_RES_H_
