// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MATERIALBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_MATERIALBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "ResTypes_generated.h"

namespace asdx {
namespace res {

struct RenderState;

struct MaterialTexture;
struct MaterialTextureBuilder;

struct MaterialBuffer;
struct MaterialBufferBuilder;

struct MaterialBinary;
struct MaterialBinaryBuilder;

enum BlendState : int8_t {
  BlendState_Opaque = 0,
  BlendState_AlphaBlend = 1,
  BlendState_Additive = 2,
  BlendState_Substract = 3,
  BlendState_Premultiplied = 4,
  BlendState_Multiply = 5,
  BlendState_Screen = 6,
  BlendState_MIN = BlendState_Opaque,
  BlendState_MAX = BlendState_Screen
};

inline const BlendState (&EnumValuesBlendState())[7] {
  static const BlendState values[] = {
    BlendState_Opaque,
    BlendState_AlphaBlend,
    BlendState_Additive,
    BlendState_Substract,
    BlendState_Premultiplied,
    BlendState_Multiply,
    BlendState_Screen
  };
  return values;
}

inline const char * const *EnumNamesBlendState() {
  static const char * const names[8] = {
    "Opaque",
    "AlphaBlend",
    "Additive",
    "Substract",
    "Premultiplied",
    "Multiply",
    "Screen",
    nullptr
  };
  return names;
}

inline const char *EnumNameBlendState(BlendState e) {
  if (::flatbuffers::IsOutRange(e, BlendState_Opaque, BlendState_Screen)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBlendState()[index];
}

enum DepthState : int8_t {
  DepthState_ReadWrite = 0,
  DepthState_ReadOnly = 1,
  DepthState_WriteOnly = 2,
  DepthState_None = 3,
  DepthState_MIN = DepthState_ReadWrite,
  DepthState_MAX = DepthState_None
};

inline const DepthState (&EnumValuesDepthState())[4] {
  static const DepthState values[] = {
    DepthState_ReadWrite,
    DepthState_ReadOnly,
    DepthState_WriteOnly,
    DepthState_None
  };
  return values;
}

inline const char * const *EnumNamesDepthState() {
  static const char * const names[5] = {
    "ReadWrite",
    "ReadOnly",
    "WriteOnly",
    "None",
    nullptr
  };
  return names;
}

inline const char *EnumNameDepthState(DepthState e) {
  if (::flatbuffers::IsOutRange(e, DepthState_ReadWrite, DepthState_None)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDepthState()[index];
}

enum RasterizerState : int8_t {
  RasterizerState_CullNone = 0,
  RasterizerState_CullBack = 1,
  RasterizerState_CullFront = 2,
  RasterizerState_Wireframe = 3,
  RasterizerState_MIN = RasterizerState_CullNone,
  RasterizerState_MAX = RasterizerState_Wireframe
};

inline const RasterizerState (&EnumValuesRasterizerState())[4] {
  static const RasterizerState values[] = {
    RasterizerState_CullNone,
    RasterizerState_CullBack,
    RasterizerState_CullFront,
    RasterizerState_Wireframe
  };
  return values;
}

inline const char * const *EnumNamesRasterizerState() {
  static const char * const names[5] = {
    "CullNone",
    "CullBack",
    "CullFront",
    "Wireframe",
    nullptr
  };
  return names;
}

inline const char *EnumNameRasterizerState(RasterizerState e) {
  if (::flatbuffers::IsOutRange(e, RasterizerState_CullNone, RasterizerState_Wireframe)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRasterizerState()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) RenderState FLATBUFFERS_FINAL_CLASS {
 private:
  int8_t Blend_;
  int8_t Depth_;
  int8_t Rasterizer_;
  uint8_t UserFlags_;

 public:
  RenderState()
      : Blend_(0),
        Depth_(0),
        Rasterizer_(0),
        UserFlags_(0) {
  }
  RenderState(asdx::res::BlendState _Blend, asdx::res::DepthState _Depth, asdx::res::RasterizerState _Rasterizer, uint8_t _UserFlags)
      : Blend_(::flatbuffers::EndianScalar(static_cast<int8_t>(_Blend))),
        Depth_(::flatbuffers::EndianScalar(static_cast<int8_t>(_Depth))),
        Rasterizer_(::flatbuffers::EndianScalar(static_cast<int8_t>(_Rasterizer))),
        UserFlags_(::flatbuffers::EndianScalar(_UserFlags)) {
  }
  asdx::res::BlendState Blend() const {
    return static_cast<asdx::res::BlendState>(::flatbuffers::EndianScalar(Blend_));
  }
  asdx::res::DepthState Depth() const {
    return static_cast<asdx::res::DepthState>(::flatbuffers::EndianScalar(Depth_));
  }
  asdx::res::RasterizerState Rasterizer() const {
    return static_cast<asdx::res::RasterizerState>(::flatbuffers::EndianScalar(Rasterizer_));
  }
  uint8_t UserFlags() const {
    return ::flatbuffers::EndianScalar(UserFlags_);
  }
};
FLATBUFFERS_STRUCT_END(RenderState, 4);

struct MaterialTexture FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialTextureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_PATH = 6
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool KeyCompareLessThan(const MaterialTexture * const o) const {
    return *Name() < *o->Name();
  }
  int KeyCompareWithValue(const char *_Name) const {
    return strcmp(Name()->c_str(), _Name);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _Name) const {
    if (Name()->c_str() < _Name) return -1;
    if (_Name < Name()->c_str()) return 1;
    return 0;
  }
  const ::flatbuffers::String *Path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(Path()) &&
           verifier.EndTable();
  }
};

struct MaterialTextureBuilder {
  typedef MaterialTexture Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(MaterialTexture::VT_NAME, Name);
  }
  void add_Path(::flatbuffers::Offset<::flatbuffers::String> Path) {
    fbb_.AddOffset(MaterialTexture::VT_PATH, Path);
  }
  explicit MaterialTextureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialTexture> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialTexture>(end);
    fbb_.Required(o, MaterialTexture::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialTexture> CreateMaterialTexture(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> Path = 0) {
  MaterialTextureBuilder builder_(_fbb);
  builder_.add_Path(Path);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialTexture> CreateMaterialTextureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    const char *Path = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Path__ = Path ? _fbb.CreateString(Path) : 0;
  return asdx::res::CreateMaterialTexture(
      _fbb,
      Name__,
      Path__);
}

struct MaterialBuffer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBufferBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DATA = 6
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool KeyCompareLessThan(const MaterialBuffer * const o) const {
    return *Name() < *o->Name();
  }
  int KeyCompareWithValue(const char *_Name) const {
    return strcmp(Name()->c_str(), _Name);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _Name) const {
    if (Name()->c_str() < _Name) return -1;
    if (_Name < Name()->c_str()) return 1;
    return 0;
  }
  const ::flatbuffers::Vector<uint8_t> *Data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(Data()) &&
           verifier.EndTable();
  }
};

struct MaterialBufferBuilder {
  typedef MaterialBuffer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(MaterialBuffer::VT_NAME, Name);
  }
  void add_Data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Data) {
    fbb_.AddOffset(MaterialBuffer::VT_DATA, Data);
  }
  explicit MaterialBufferBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialBuffer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialBuffer>(end);
    fbb_.Required(o, MaterialBuffer::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialBuffer> CreateMaterialBuffer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Data = 0) {
  MaterialBufferBuilder builder_(_fbb);
  builder_.add_Data(Data);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialBuffer> CreateMaterialBufferDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    const std::vector<uint8_t> *Data = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Data__ = Data ? _fbb.CreateVector<uint8_t>(*Data) : 0;
  return asdx::res::CreateMaterialBuffer(
      _fbb,
      Name__,
      Data__);
}

struct MaterialBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_PIXELSHADER = 6,
    VT_STATES = 8,
    VT_BUFFERS = 10,
    VT_TEXTURES = 12
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::String *PixelShader() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PIXELSHADER);
  }
  const asdx::res::RenderState *States() const {
    return GetStruct<const asdx::res::RenderState *>(VT_STATES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialBuffer>> *Buffers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialBuffer>> *>(VT_BUFFERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialTexture>> *Textures() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialTexture>> *>(VT_TEXTURES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_PIXELSHADER) &&
           verifier.VerifyString(PixelShader()) &&
           VerifyField<asdx::res::RenderState>(verifier, VT_STATES, 1) &&
           VerifyOffset(verifier, VT_BUFFERS) &&
           verifier.VerifyVector(Buffers()) &&
           verifier.VerifyVectorOfTables(Buffers()) &&
           VerifyOffset(verifier, VT_TEXTURES) &&
           verifier.VerifyVector(Textures()) &&
           verifier.VerifyVectorOfTables(Textures()) &&
           verifier.EndTable();
  }
};

struct MaterialBinaryBuilder {
  typedef MaterialBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(MaterialBinary::VT_VERSION, Version, 0);
  }
  void add_PixelShader(::flatbuffers::Offset<::flatbuffers::String> PixelShader) {
    fbb_.AddOffset(MaterialBinary::VT_PIXELSHADER, PixelShader);
  }
  void add_States(const asdx::res::RenderState *States) {
    fbb_.AddStruct(MaterialBinary::VT_STATES, States);
  }
  void add_Buffers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialBuffer>>> Buffers) {
    fbb_.AddOffset(MaterialBinary::VT_BUFFERS, Buffers);
  }
  void add_Textures(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialTexture>>> Textures) {
    fbb_.AddOffset(MaterialBinary::VT_TEXTURES, Textures);
  }
  explicit MaterialBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialBinary> CreateMaterialBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> PixelShader = 0,
    const asdx::res::RenderState *States = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialBuffer>>> Buffers = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MaterialTexture>>> Textures = 0) {
  MaterialBinaryBuilder builder_(_fbb);
  builder_.add_Textures(Textures);
  builder_.add_Buffers(Buffers);
  builder_.add_States(States);
  builder_.add_PixelShader(PixelShader);
  builder_.add_Version(Version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialBinary> CreateMaterialBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    const char *PixelShader = nullptr,
    const asdx::res::RenderState *States = nullptr,
    std::vector<::flatbuffers::Offset<asdx::res::MaterialBuffer>> *Buffers = nullptr,
    std::vector<::flatbuffers::Offset<asdx::res::MaterialTexture>> *Textures = nullptr) {
  auto PixelShader__ = PixelShader ? _fbb.CreateString(PixelShader) : 0;
  auto Buffers__ = Buffers ? _fbb.CreateVectorOfSortedTables<asdx::res::MaterialBuffer>(Buffers) : 0;
  auto Textures__ = Textures ? _fbb.CreateVectorOfSortedTables<asdx::res::MaterialTexture>(Textures) : 0;
  return asdx::res::CreateMaterialBinary(
      _fbb,
      Version,
      PixelShader__,
      States,
      Buffers__,
      Textures__);
}

inline const asdx::res::MaterialBinary *GetMaterialBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::MaterialBinary>(buf);
}

inline const asdx::res::MaterialBinary *GetSizePrefixedMaterialBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::MaterialBinary>(buf);
}

inline bool VerifyMaterialBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::MaterialBinary>(nullptr);
}

inline bool VerifySizePrefixedMaterialBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::MaterialBinary>(nullptr);
}

inline void FinishMaterialBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MaterialBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMaterialBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MaterialBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_MATERIALBINARY_ASDX_RES_H_
