// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MODELBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_MODELBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace asdx {
namespace res {

struct Float2;

struct Float3;

struct Float4;

struct Uint4;

struct Unorm4;

struct Float4x4;

struct Bone;
struct BoneBuilder;

struct Mesh;
struct MeshBuilder;

struct ModelBinary;
struct ModelBinaryBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float2 FLATBUFFERS_FINAL_CLASS {
 private:
  float X_;
  float Y_;

 public:
  Float2()
      : X_(0),
        Y_(0) {
  }
  Float2(float _X, float _Y)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)) {
  }
  float X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  float Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
};
FLATBUFFERS_STRUCT_END(Float2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float3 FLATBUFFERS_FINAL_CLASS {
 private:
  float X_;
  float Y_;
  float Z_;

 public:
  Float3()
      : X_(0),
        Y_(0),
        Z_(0) {
  }
  Float3(float _X, float _Y, float _Z)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)) {
  }
  float X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  float Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  float Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
};
FLATBUFFERS_STRUCT_END(Float3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float4 FLATBUFFERS_FINAL_CLASS {
 private:
  float X_;
  float Y_;
  float Z_;
  float W_;

 public:
  Float4()
      : X_(0),
        Y_(0),
        Z_(0),
        W_(0) {
  }
  Float4(float _X, float _Y, float _Z, float _W)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)),
        W_(::flatbuffers::EndianScalar(_W)) {
  }
  float X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  float Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  float Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
  float W() const {
    return ::flatbuffers::EndianScalar(W_);
  }
};
FLATBUFFERS_STRUCT_END(Float4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Uint4 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t X_;
  uint32_t Y_;
  uint32_t Z_;
  uint32_t W_;

 public:
  Uint4()
      : X_(0),
        Y_(0),
        Z_(0),
        W_(0) {
  }
  Uint4(uint32_t _X, uint32_t _Y, uint32_t _Z, uint32_t _W)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)),
        W_(::flatbuffers::EndianScalar(_W)) {
  }
  uint32_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  uint32_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  uint32_t Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
  uint32_t W() const {
    return ::flatbuffers::EndianScalar(W_);
  }
};
FLATBUFFERS_STRUCT_END(Uint4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Unorm4 FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t X_;
  uint8_t Y_;
  uint8_t Z_;
  uint8_t W_;

 public:
  Unorm4()
      : X_(0),
        Y_(0),
        Z_(0),
        W_(0) {
  }
  Unorm4(uint8_t _X, uint8_t _Y, uint8_t _Z, uint8_t _W)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)),
        W_(::flatbuffers::EndianScalar(_W)) {
  }
  uint8_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  uint8_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  uint8_t Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
  uint8_t W() const {
    return ::flatbuffers::EndianScalar(W_);
  }
};
FLATBUFFERS_STRUCT_END(Unorm4, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float4x4 FLATBUFFERS_FINAL_CLASS {
 private:
  float M11_;
  float M12_;
  float M13_;
  float M14_;
  float M21_;
  float M22_;
  float M23_;
  float M24_;
  float M31_;
  float M32_;
  float M33_;
  float M34_;
  float M41_;
  float M42_;
  float M43_;
  float M44_;

 public:
  Float4x4()
      : M11_(0),
        M12_(0),
        M13_(0),
        M14_(0),
        M21_(0),
        M22_(0),
        M23_(0),
        M24_(0),
        M31_(0),
        M32_(0),
        M33_(0),
        M34_(0),
        M41_(0),
        M42_(0),
        M43_(0),
        M44_(0) {
  }
  Float4x4(float _M11, float _M12, float _M13, float _M14, float _M21, float _M22, float _M23, float _M24, float _M31, float _M32, float _M33, float _M34, float _M41, float _M42, float _M43, float _M44)
      : M11_(::flatbuffers::EndianScalar(_M11)),
        M12_(::flatbuffers::EndianScalar(_M12)),
        M13_(::flatbuffers::EndianScalar(_M13)),
        M14_(::flatbuffers::EndianScalar(_M14)),
        M21_(::flatbuffers::EndianScalar(_M21)),
        M22_(::flatbuffers::EndianScalar(_M22)),
        M23_(::flatbuffers::EndianScalar(_M23)),
        M24_(::flatbuffers::EndianScalar(_M24)),
        M31_(::flatbuffers::EndianScalar(_M31)),
        M32_(::flatbuffers::EndianScalar(_M32)),
        M33_(::flatbuffers::EndianScalar(_M33)),
        M34_(::flatbuffers::EndianScalar(_M34)),
        M41_(::flatbuffers::EndianScalar(_M41)),
        M42_(::flatbuffers::EndianScalar(_M42)),
        M43_(::flatbuffers::EndianScalar(_M43)),
        M44_(::flatbuffers::EndianScalar(_M44)) {
  }
  float M11() const {
    return ::flatbuffers::EndianScalar(M11_);
  }
  float M12() const {
    return ::flatbuffers::EndianScalar(M12_);
  }
  float M13() const {
    return ::flatbuffers::EndianScalar(M13_);
  }
  float M14() const {
    return ::flatbuffers::EndianScalar(M14_);
  }
  float M21() const {
    return ::flatbuffers::EndianScalar(M21_);
  }
  float M22() const {
    return ::flatbuffers::EndianScalar(M22_);
  }
  float M23() const {
    return ::flatbuffers::EndianScalar(M23_);
  }
  float M24() const {
    return ::flatbuffers::EndianScalar(M24_);
  }
  float M31() const {
    return ::flatbuffers::EndianScalar(M31_);
  }
  float M32() const {
    return ::flatbuffers::EndianScalar(M32_);
  }
  float M33() const {
    return ::flatbuffers::EndianScalar(M33_);
  }
  float M34() const {
    return ::flatbuffers::EndianScalar(M34_);
  }
  float M41() const {
    return ::flatbuffers::EndianScalar(M41_);
  }
  float M42() const {
    return ::flatbuffers::EndianScalar(M42_);
  }
  float M43() const {
    return ::flatbuffers::EndianScalar(M43_);
  }
  float M44() const {
    return ::flatbuffers::EndianScalar(M44_);
  }
};
FLATBUFFERS_STRUCT_END(Float4x4, 64);

struct Bone FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_OFFSETMATRIX = 6
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool KeyCompareLessThan(const Bone * const o) const {
    return *Name() < *o->Name();
  }
  int KeyCompareWithValue(const char *_Name) const {
    return strcmp(Name()->c_str(), _Name);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _Name) const {
    if (Name()->c_str() < _Name) return -1;
    if (_Name < Name()->c_str()) return 1;
    return 0;
  }
  const asdx::res::Float4x4 *OffsetMatrix() const {
    return GetStruct<const asdx::res::Float4x4 *>(VT_OFFSETMATRIX);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyField<asdx::res::Float4x4>(verifier, VT_OFFSETMATRIX, 4) &&
           verifier.EndTable();
  }
};

struct BoneBuilder {
  typedef Bone Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(Bone::VT_NAME, Name);
  }
  void add_OffsetMatrix(const asdx::res::Float4x4 *OffsetMatrix) {
    fbb_.AddStruct(Bone::VT_OFFSETMATRIX, OffsetMatrix);
  }
  explicit BoneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Bone> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Bone>(end);
    fbb_.Required(o, Bone::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<Bone> CreateBone(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    const asdx::res::Float4x4 *OffsetMatrix = nullptr) {
  BoneBuilder builder_(_fbb);
  builder_.add_OffsetMatrix(OffsetMatrix);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Bone> CreateBoneDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    const asdx::res::Float4x4 *OffsetMatrix = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  return asdx::res::CreateBone(
      _fbb,
      Name__,
      OffsetMatrix);
}

struct Mesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_MATERIALID = 6,
    VT_POSITIONS = 8,
    VT_NORMALS = 10,
    VT_TANGENTS = 12,
    VT_COLORS = 14,
    VT_TEXCOORDS = 16,
    VT_BONEWEIGHTS = 18,
    VT_BONEINDICES = 20,
    VT_VERTEXINDICES = 22
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t MaterialId() const {
    return GetField<uint32_t>(VT_MATERIALID, 0);
  }
  const ::flatbuffers::Vector<const asdx::res::Float3 *> *Positions() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float3 *> *>(VT_POSITIONS);
  }
  const ::flatbuffers::Vector<const asdx::res::Float3 *> *Normals() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float3 *> *>(VT_NORMALS);
  }
  const ::flatbuffers::Vector<const asdx::res::Float4 *> *Tangents() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float4 *> *>(VT_TANGENTS);
  }
  const ::flatbuffers::Vector<const asdx::res::Unorm4 *> *Colors() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Unorm4 *> *>(VT_COLORS);
  }
  const ::flatbuffers::Vector<const asdx::res::Float2 *> *TexCoords() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float2 *> *>(VT_TEXCOORDS);
  }
  const ::flatbuffers::Vector<const asdx::res::Float4 *> *BoneWeights() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float4 *> *>(VT_BONEWEIGHTS);
  }
  const ::flatbuffers::Vector<const asdx::res::Uint4 *> *BoneIndices() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Uint4 *> *>(VT_BONEINDICES);
  }
  const ::flatbuffers::Vector<uint32_t> *VertexIndices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_VERTEXINDICES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyField<uint32_t>(verifier, VT_MATERIALID, 4) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(Positions()) &&
           VerifyOffset(verifier, VT_NORMALS) &&
           verifier.VerifyVector(Normals()) &&
           VerifyOffset(verifier, VT_TANGENTS) &&
           verifier.VerifyVector(Tangents()) &&
           VerifyOffset(verifier, VT_COLORS) &&
           verifier.VerifyVector(Colors()) &&
           VerifyOffset(verifier, VT_TEXCOORDS) &&
           verifier.VerifyVector(TexCoords()) &&
           VerifyOffset(verifier, VT_BONEWEIGHTS) &&
           verifier.VerifyVector(BoneWeights()) &&
           VerifyOffset(verifier, VT_BONEINDICES) &&
           verifier.VerifyVector(BoneIndices()) &&
           VerifyOffset(verifier, VT_VERTEXINDICES) &&
           verifier.VerifyVector(VertexIndices()) &&
           verifier.EndTable();
  }
};

struct MeshBuilder {
  typedef Mesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(Mesh::VT_NAME, Name);
  }
  void add_MaterialId(uint32_t MaterialId) {
    fbb_.AddElement<uint32_t>(Mesh::VT_MATERIALID, MaterialId, 0);
  }
  void add_Positions(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3 *>> Positions) {
    fbb_.AddOffset(Mesh::VT_POSITIONS, Positions);
  }
  void add_Normals(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3 *>> Normals) {
    fbb_.AddOffset(Mesh::VT_NORMALS, Normals);
  }
  void add_Tangents(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float4 *>> Tangents) {
    fbb_.AddOffset(Mesh::VT_TANGENTS, Tangents);
  }
  void add_Colors(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Unorm4 *>> Colors) {
    fbb_.AddOffset(Mesh::VT_COLORS, Colors);
  }
  void add_TexCoords(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float2 *>> TexCoords) {
    fbb_.AddOffset(Mesh::VT_TEXCOORDS, TexCoords);
  }
  void add_BoneWeights(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float4 *>> BoneWeights) {
    fbb_.AddOffset(Mesh::VT_BONEWEIGHTS, BoneWeights);
  }
  void add_BoneIndices(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Uint4 *>> BoneIndices) {
    fbb_.AddOffset(Mesh::VT_BONEINDICES, BoneIndices);
  }
  void add_VertexIndices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> VertexIndices) {
    fbb_.AddOffset(Mesh::VT_VERTEXINDICES, VertexIndices);
  }
  explicit MeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mesh> CreateMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    uint32_t MaterialId = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3 *>> Positions = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3 *>> Normals = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float4 *>> Tangents = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Unorm4 *>> Colors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float2 *>> TexCoords = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float4 *>> BoneWeights = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Uint4 *>> BoneIndices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> VertexIndices = 0) {
  MeshBuilder builder_(_fbb);
  builder_.add_VertexIndices(VertexIndices);
  builder_.add_BoneIndices(BoneIndices);
  builder_.add_BoneWeights(BoneWeights);
  builder_.add_TexCoords(TexCoords);
  builder_.add_Colors(Colors);
  builder_.add_Tangents(Tangents);
  builder_.add_Normals(Normals);
  builder_.add_Positions(Positions);
  builder_.add_MaterialId(MaterialId);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Mesh> CreateMeshDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    uint32_t MaterialId = 0,
    const std::vector<asdx::res::Float3> *Positions = nullptr,
    const std::vector<asdx::res::Float3> *Normals = nullptr,
    const std::vector<asdx::res::Float4> *Tangents = nullptr,
    const std::vector<asdx::res::Unorm4> *Colors = nullptr,
    const std::vector<asdx::res::Float2> *TexCoords = nullptr,
    const std::vector<asdx::res::Float4> *BoneWeights = nullptr,
    const std::vector<asdx::res::Uint4> *BoneIndices = nullptr,
    const std::vector<uint32_t> *VertexIndices = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Positions__ = Positions ? _fbb.CreateVectorOfStructs<asdx::res::Float3>(*Positions) : 0;
  auto Normals__ = Normals ? _fbb.CreateVectorOfStructs<asdx::res::Float3>(*Normals) : 0;
  auto Tangents__ = Tangents ? _fbb.CreateVectorOfStructs<asdx::res::Float4>(*Tangents) : 0;
  auto Colors__ = Colors ? _fbb.CreateVectorOfStructs<asdx::res::Unorm4>(*Colors) : 0;
  auto TexCoords__ = TexCoords ? _fbb.CreateVectorOfStructs<asdx::res::Float2>(*TexCoords) : 0;
  auto BoneWeights__ = BoneWeights ? _fbb.CreateVectorOfStructs<asdx::res::Float4>(*BoneWeights) : 0;
  auto BoneIndices__ = BoneIndices ? _fbb.CreateVectorOfStructs<asdx::res::Uint4>(*BoneIndices) : 0;
  auto VertexIndices__ = VertexIndices ? _fbb.CreateVector<uint32_t>(*VertexIndices) : 0;
  return asdx::res::CreateMesh(
      _fbb,
      Name__,
      MaterialId,
      Positions__,
      Normals__,
      Tangents__,
      Colors__,
      TexCoords__,
      BoneWeights__,
      BoneIndices__,
      VertexIndices__);
}

struct ModelBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_MESHES = 6,
    VT_MATERIALS = 8,
    VT_BONES = 10
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Mesh>> *Meshes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Mesh>> *>(VT_MESHES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *Materials() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_MATERIALS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Bone>> *Bones() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Bone>> *>(VT_BONES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_MESHES) &&
           verifier.VerifyVector(Meshes()) &&
           verifier.VerifyVectorOfTables(Meshes()) &&
           VerifyOffset(verifier, VT_MATERIALS) &&
           verifier.VerifyVector(Materials()) &&
           verifier.VerifyVectorOfStrings(Materials()) &&
           VerifyOffset(verifier, VT_BONES) &&
           verifier.VerifyVector(Bones()) &&
           verifier.VerifyVectorOfTables(Bones()) &&
           verifier.EndTable();
  }
};

struct ModelBinaryBuilder {
  typedef ModelBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(ModelBinary::VT_VERSION, Version, 0);
  }
  void add_Meshes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Mesh>>> Meshes) {
    fbb_.AddOffset(ModelBinary::VT_MESHES, Meshes);
  }
  void add_Materials(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> Materials) {
    fbb_.AddOffset(ModelBinary::VT_MATERIALS, Materials);
  }
  void add_Bones(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Bone>>> Bones) {
    fbb_.AddOffset(ModelBinary::VT_BONES, Bones);
  }
  explicit ModelBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelBinary> CreateModelBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Mesh>>> Meshes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> Materials = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Bone>>> Bones = 0) {
  ModelBinaryBuilder builder_(_fbb);
  builder_.add_Bones(Bones);
  builder_.add_Materials(Materials);
  builder_.add_Meshes(Meshes);
  builder_.add_Version(Version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModelBinary> CreateModelBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    const std::vector<::flatbuffers::Offset<asdx::res::Mesh>> *Meshes = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *Materials = nullptr,
    std::vector<::flatbuffers::Offset<asdx::res::Bone>> *Bones = nullptr) {
  auto Meshes__ = Meshes ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::Mesh>>(*Meshes) : 0;
  auto Materials__ = Materials ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*Materials) : 0;
  auto Bones__ = Bones ? _fbb.CreateVectorOfSortedTables<asdx::res::Bone>(Bones) : 0;
  return asdx::res::CreateModelBinary(
      _fbb,
      Version,
      Meshes__,
      Materials__,
      Bones__);
}

inline const asdx::res::ModelBinary *GetModelBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::ModelBinary>(buf);
}

inline const asdx::res::ModelBinary *GetSizePrefixedModelBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::ModelBinary>(buf);
}

inline bool VerifyModelBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::ModelBinary>(nullptr);
}

inline bool VerifySizePrefixedModelBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::ModelBinary>(nullptr);
}

inline void FinishModelBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::ModelBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedModelBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::ModelBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_MODELBINARY_ASDX_RES_H_
