// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MODELPREFABBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_MODELPREFABBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "ResTypes_generated.h"

namespace asdx {
namespace res {

struct MeshMaterial;
struct MeshMaterialBuilder;

struct ModelPrefabBinary;
struct ModelPrefabBinaryBuilder;

struct MeshMaterial FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshMaterialBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_PATH = 6
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool KeyCompareLessThan(const MeshMaterial * const o) const {
    return *Name() < *o->Name();
  }
  int KeyCompareWithValue(const char *_Name) const {
    return strcmp(Name()->c_str(), _Name);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _Name) const {
    if (Name()->c_str() < _Name) return -1;
    if (_Name < Name()->c_str()) return 1;
    return 0;
  }
  const ::flatbuffers::String *Path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(Path()) &&
           verifier.EndTable();
  }
};

struct MeshMaterialBuilder {
  typedef MeshMaterial Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(MeshMaterial::VT_NAME, Name);
  }
  void add_Path(::flatbuffers::Offset<::flatbuffers::String> Path) {
    fbb_.AddOffset(MeshMaterial::VT_PATH, Path);
  }
  explicit MeshMaterialBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshMaterial> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshMaterial>(end);
    fbb_.Required(o, MeshMaterial::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshMaterial> CreateMeshMaterial(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> Path = 0) {
  MeshMaterialBuilder builder_(_fbb);
  builder_.add_Path(Path);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshMaterial> CreateMeshMaterialDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    const char *Path = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Path__ = Path ? _fbb.CreateString(Path) : 0;
  return asdx::res::CreateMeshMaterial(
      _fbb,
      Name__,
      Path__);
}

struct ModelPrefabBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelPrefabBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_MODELPATH = 6,
    VT_MATERIALS = 8
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::String *ModelPath() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODELPATH);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MeshMaterial>> *Materials() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MeshMaterial>> *>(VT_MATERIALS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_MODELPATH) &&
           verifier.VerifyString(ModelPath()) &&
           VerifyOffset(verifier, VT_MATERIALS) &&
           verifier.VerifyVector(Materials()) &&
           verifier.VerifyVectorOfTables(Materials()) &&
           verifier.EndTable();
  }
};

struct ModelPrefabBinaryBuilder {
  typedef ModelPrefabBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(ModelPrefabBinary::VT_VERSION, Version, 0);
  }
  void add_ModelPath(::flatbuffers::Offset<::flatbuffers::String> ModelPath) {
    fbb_.AddOffset(ModelPrefabBinary::VT_MODELPATH, ModelPath);
  }
  void add_Materials(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MeshMaterial>>> Materials) {
    fbb_.AddOffset(ModelPrefabBinary::VT_MATERIALS, Materials);
  }
  explicit ModelPrefabBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelPrefabBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelPrefabBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelPrefabBinary> CreateModelPrefabBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ModelPath = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MeshMaterial>>> Materials = 0) {
  ModelPrefabBinaryBuilder builder_(_fbb);
  builder_.add_Materials(Materials);
  builder_.add_ModelPath(ModelPath);
  builder_.add_Version(Version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModelPrefabBinary> CreateModelPrefabBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    const char *ModelPath = nullptr,
    std::vector<::flatbuffers::Offset<asdx::res::MeshMaterial>> *Materials = nullptr) {
  auto ModelPath__ = ModelPath ? _fbb.CreateString(ModelPath) : 0;
  auto Materials__ = Materials ? _fbb.CreateVectorOfSortedTables<asdx::res::MeshMaterial>(Materials) : 0;
  return asdx::res::CreateModelPrefabBinary(
      _fbb,
      Version,
      ModelPath__,
      Materials__);
}

inline const asdx::res::ModelPrefabBinary *GetModelPrefabBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::ModelPrefabBinary>(buf);
}

inline const asdx::res::ModelPrefabBinary *GetSizePrefixedModelPrefabBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::ModelPrefabBinary>(buf);
}

inline bool VerifyModelPrefabBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::ModelPrefabBinary>(nullptr);
}

inline bool VerifySizePrefixedModelPrefabBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::ModelPrefabBinary>(nullptr);
}

inline void FinishModelPrefabBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::ModelPrefabBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedModelPrefabBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::ModelPrefabBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_MODELPREFABBINARY_ASDX_RES_H_
