// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MODELBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_MODELBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "ResTypes_generated.h"

namespace asdx {
namespace res {

struct Bone;
struct BoneBuilder;

struct Mesh;
struct MeshBuilder;

struct Material;
struct MaterialBuilder;

struct ModelBatch;
struct ModelBatchBuilder;

struct ModelBinary;
struct ModelBinaryBuilder;

enum AlphaType : uint8_t {
  AlphaType_Opaque = 0,
  AlphaType_Mask = 1,
  AlphaType_Blend = 2,
  AlphaType_MIN = AlphaType_Opaque,
  AlphaType_MAX = AlphaType_Blend
};

inline const AlphaType (&EnumValuesAlphaType())[3] {
  static const AlphaType values[] = {
    AlphaType_Opaque,
    AlphaType_Mask,
    AlphaType_Blend
  };
  return values;
}

inline const char * const *EnumNamesAlphaType() {
  static const char * const names[4] = {
    "Opaque",
    "Mask",
    "Blend",
    nullptr
  };
  return names;
}

inline const char *EnumNameAlphaType(AlphaType e) {
  if (::flatbuffers::IsOutRange(e, AlphaType_Opaque, AlphaType_Blend)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAlphaType()[index];
}

struct Bone FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_PARENT = 6,
    VT_BINDPOSE = 8,
    VT_INVERSEBINDPOSE = 10,
    VT_CHILDREN = 12
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t Parent() const {
    return GetField<int32_t>(VT_PARENT, 0);
  }
  const asdx::res::Float3x4 *BindPose() const {
    return GetStruct<const asdx::res::Float3x4 *>(VT_BINDPOSE);
  }
  const asdx::res::Float3x4 *InverseBindPose() const {
    return GetStruct<const asdx::res::Float3x4 *>(VT_INVERSEBINDPOSE);
  }
  const ::flatbuffers::Vector<int32_t> *Children() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_CHILDREN);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyField<int32_t>(verifier, VT_PARENT, 4) &&
           VerifyField<asdx::res::Float3x4>(verifier, VT_BINDPOSE, 4) &&
           VerifyField<asdx::res::Float3x4>(verifier, VT_INVERSEBINDPOSE, 4) &&
           VerifyOffset(verifier, VT_CHILDREN) &&
           verifier.VerifyVector(Children()) &&
           verifier.EndTable();
  }
};

struct BoneBuilder {
  typedef Bone Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(Bone::VT_NAME, Name);
  }
  void add_Parent(int32_t Parent) {
    fbb_.AddElement<int32_t>(Bone::VT_PARENT, Parent, 0);
  }
  void add_BindPose(const asdx::res::Float3x4 *BindPose) {
    fbb_.AddStruct(Bone::VT_BINDPOSE, BindPose);
  }
  void add_InverseBindPose(const asdx::res::Float3x4 *InverseBindPose) {
    fbb_.AddStruct(Bone::VT_INVERSEBINDPOSE, InverseBindPose);
  }
  void add_Children(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> Children) {
    fbb_.AddOffset(Bone::VT_CHILDREN, Children);
  }
  explicit BoneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Bone> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Bone>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Bone> CreateBone(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    int32_t Parent = 0,
    const asdx::res::Float3x4 *BindPose = nullptr,
    const asdx::res::Float3x4 *InverseBindPose = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> Children = 0) {
  BoneBuilder builder_(_fbb);
  builder_.add_Children(Children);
  builder_.add_InverseBindPose(InverseBindPose);
  builder_.add_BindPose(BindPose);
  builder_.add_Parent(Parent);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Bone> CreateBoneDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    int32_t Parent = 0,
    const asdx::res::Float3x4 *BindPose = nullptr,
    const asdx::res::Float3x4 *InverseBindPose = nullptr,
    const std::vector<int32_t> *Children = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Children__ = Children ? _fbb.CreateVector<int32_t>(*Children) : 0;
  return asdx::res::CreateBone(
      _fbb,
      Name__,
      Parent,
      BindPose,
      InverseBindPose,
      Children__);
}

struct Mesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_MATERIALID = 6,
    VT_POSITIONS = 8,
    VT_NORMALS = 10,
    VT_TANGENTS = 12,
    VT_COLORS = 14,
    VT_TEXCOORDS = 16,
    VT_BONEWEIGHTS = 18,
    VT_BONEINDICES = 20,
    VT_VERTEXINDICES = 22,
    VT_BOUNDSPHERE = 24,
    VT_BOUNDBOX = 26
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t MaterialId() const {
    return GetField<uint32_t>(VT_MATERIALID, 0);
  }
  const ::flatbuffers::Vector<const asdx::res::Float3 *> *Positions() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float3 *> *>(VT_POSITIONS);
  }
  const ::flatbuffers::Vector<const asdx::res::Float3 *> *Normals() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float3 *> *>(VT_NORMALS);
  }
  const ::flatbuffers::Vector<const asdx::res::Float4 *> *Tangents() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float4 *> *>(VT_TANGENTS);
  }
  const ::flatbuffers::Vector<const asdx::res::Unorm4 *> *Colors() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Unorm4 *> *>(VT_COLORS);
  }
  const ::flatbuffers::Vector<const asdx::res::Float2 *> *TexCoords() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float2 *> *>(VT_TEXCOORDS);
  }
  const ::flatbuffers::Vector<const asdx::res::Float4 *> *BoneWeights() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float4 *> *>(VT_BONEWEIGHTS);
  }
  const ::flatbuffers::Vector<const asdx::res::Uint4 *> *BoneIndices() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Uint4 *> *>(VT_BONEINDICES);
  }
  const ::flatbuffers::Vector<uint32_t> *VertexIndices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_VERTEXINDICES);
  }
  const asdx::res::BoundingSphere *BoundSphere() const {
    return GetStruct<const asdx::res::BoundingSphere *>(VT_BOUNDSPHERE);
  }
  const asdx::res::BoundingBox *BoundBox() const {
    return GetStruct<const asdx::res::BoundingBox *>(VT_BOUNDBOX);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyField<uint32_t>(verifier, VT_MATERIALID, 4) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(Positions()) &&
           VerifyOffset(verifier, VT_NORMALS) &&
           verifier.VerifyVector(Normals()) &&
           VerifyOffset(verifier, VT_TANGENTS) &&
           verifier.VerifyVector(Tangents()) &&
           VerifyOffset(verifier, VT_COLORS) &&
           verifier.VerifyVector(Colors()) &&
           VerifyOffset(verifier, VT_TEXCOORDS) &&
           verifier.VerifyVector(TexCoords()) &&
           VerifyOffset(verifier, VT_BONEWEIGHTS) &&
           verifier.VerifyVector(BoneWeights()) &&
           VerifyOffset(verifier, VT_BONEINDICES) &&
           verifier.VerifyVector(BoneIndices()) &&
           VerifyOffset(verifier, VT_VERTEXINDICES) &&
           verifier.VerifyVector(VertexIndices()) &&
           VerifyField<asdx::res::BoundingSphere>(verifier, VT_BOUNDSPHERE, 4) &&
           VerifyField<asdx::res::BoundingBox>(verifier, VT_BOUNDBOX, 4) &&
           verifier.EndTable();
  }
};

struct MeshBuilder {
  typedef Mesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(Mesh::VT_NAME, Name);
  }
  void add_MaterialId(uint32_t MaterialId) {
    fbb_.AddElement<uint32_t>(Mesh::VT_MATERIALID, MaterialId, 0);
  }
  void add_Positions(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3 *>> Positions) {
    fbb_.AddOffset(Mesh::VT_POSITIONS, Positions);
  }
  void add_Normals(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3 *>> Normals) {
    fbb_.AddOffset(Mesh::VT_NORMALS, Normals);
  }
  void add_Tangents(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float4 *>> Tangents) {
    fbb_.AddOffset(Mesh::VT_TANGENTS, Tangents);
  }
  void add_Colors(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Unorm4 *>> Colors) {
    fbb_.AddOffset(Mesh::VT_COLORS, Colors);
  }
  void add_TexCoords(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float2 *>> TexCoords) {
    fbb_.AddOffset(Mesh::VT_TEXCOORDS, TexCoords);
  }
  void add_BoneWeights(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float4 *>> BoneWeights) {
    fbb_.AddOffset(Mesh::VT_BONEWEIGHTS, BoneWeights);
  }
  void add_BoneIndices(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Uint4 *>> BoneIndices) {
    fbb_.AddOffset(Mesh::VT_BONEINDICES, BoneIndices);
  }
  void add_VertexIndices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> VertexIndices) {
    fbb_.AddOffset(Mesh::VT_VERTEXINDICES, VertexIndices);
  }
  void add_BoundSphere(const asdx::res::BoundingSphere *BoundSphere) {
    fbb_.AddStruct(Mesh::VT_BOUNDSPHERE, BoundSphere);
  }
  void add_BoundBox(const asdx::res::BoundingBox *BoundBox) {
    fbb_.AddStruct(Mesh::VT_BOUNDBOX, BoundBox);
  }
  explicit MeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mesh> CreateMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    uint32_t MaterialId = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3 *>> Positions = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3 *>> Normals = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float4 *>> Tangents = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Unorm4 *>> Colors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float2 *>> TexCoords = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float4 *>> BoneWeights = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Uint4 *>> BoneIndices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> VertexIndices = 0,
    const asdx::res::BoundingSphere *BoundSphere = nullptr,
    const asdx::res::BoundingBox *BoundBox = nullptr) {
  MeshBuilder builder_(_fbb);
  builder_.add_BoundBox(BoundBox);
  builder_.add_BoundSphere(BoundSphere);
  builder_.add_VertexIndices(VertexIndices);
  builder_.add_BoneIndices(BoneIndices);
  builder_.add_BoneWeights(BoneWeights);
  builder_.add_TexCoords(TexCoords);
  builder_.add_Colors(Colors);
  builder_.add_Tangents(Tangents);
  builder_.add_Normals(Normals);
  builder_.add_Positions(Positions);
  builder_.add_MaterialId(MaterialId);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Mesh> CreateMeshDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    uint32_t MaterialId = 0,
    const std::vector<asdx::res::Float3> *Positions = nullptr,
    const std::vector<asdx::res::Float3> *Normals = nullptr,
    const std::vector<asdx::res::Float4> *Tangents = nullptr,
    const std::vector<asdx::res::Unorm4> *Colors = nullptr,
    const std::vector<asdx::res::Float2> *TexCoords = nullptr,
    const std::vector<asdx::res::Float4> *BoneWeights = nullptr,
    const std::vector<asdx::res::Uint4> *BoneIndices = nullptr,
    const std::vector<uint32_t> *VertexIndices = nullptr,
    const asdx::res::BoundingSphere *BoundSphere = nullptr,
    const asdx::res::BoundingBox *BoundBox = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Positions__ = Positions ? _fbb.CreateVectorOfStructs<asdx::res::Float3>(*Positions) : 0;
  auto Normals__ = Normals ? _fbb.CreateVectorOfStructs<asdx::res::Float3>(*Normals) : 0;
  auto Tangents__ = Tangents ? _fbb.CreateVectorOfStructs<asdx::res::Float4>(*Tangents) : 0;
  auto Colors__ = Colors ? _fbb.CreateVectorOfStructs<asdx::res::Unorm4>(*Colors) : 0;
  auto TexCoords__ = TexCoords ? _fbb.CreateVectorOfStructs<asdx::res::Float2>(*TexCoords) : 0;
  auto BoneWeights__ = BoneWeights ? _fbb.CreateVectorOfStructs<asdx::res::Float4>(*BoneWeights) : 0;
  auto BoneIndices__ = BoneIndices ? _fbb.CreateVectorOfStructs<asdx::res::Uint4>(*BoneIndices) : 0;
  auto VertexIndices__ = VertexIndices ? _fbb.CreateVector<uint32_t>(*VertexIndices) : 0;
  return asdx::res::CreateMesh(
      _fbb,
      Name__,
      MaterialId,
      Positions__,
      Normals__,
      Tangents__,
      Colors__,
      TexCoords__,
      BoneWeights__,
      BoneIndices__,
      VertexIndices__,
      BoundSphere,
      BoundBox);
}

struct Material FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_BASECOLORFACTOR = 6,
    VT_ALPHA = 8,
    VT_OCCLUSIONFACTOR = 10,
    VT_ROUGHNESSFACTOR = 12,
    VT_METALNESSFACTOR = 14,
    VT_IOR = 16,
    VT_EMISSIVEFACTOR = 18,
    VT_BASECOLORMAP = 20,
    VT_NORMALMAP = 22,
    VT_ORMMAP = 24,
    VT_EMISSIVEMAP = 26,
    VT_ALPHAMODE = 28,
    VT_ALPHACUTOFF = 30,
    VT_TWOSIDED = 32
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const asdx::res::Float3 *BaseColorFactor() const {
    return GetStruct<const asdx::res::Float3 *>(VT_BASECOLORFACTOR);
  }
  float Alpha() const {
    return GetField<float>(VT_ALPHA, 0.0f);
  }
  float OcclusionFactor() const {
    return GetField<float>(VT_OCCLUSIONFACTOR, 0.0f);
  }
  float RoughnessFactor() const {
    return GetField<float>(VT_ROUGHNESSFACTOR, 0.0f);
  }
  float MetalnessFactor() const {
    return GetField<float>(VT_METALNESSFACTOR, 0.0f);
  }
  float Ior() const {
    return GetField<float>(VT_IOR, 0.0f);
  }
  const asdx::res::Float3 *EmissiveFactor() const {
    return GetStruct<const asdx::res::Float3 *>(VT_EMISSIVEFACTOR);
  }
  const ::flatbuffers::String *BaseColorMap() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BASECOLORMAP);
  }
  const ::flatbuffers::String *NormalMap() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NORMALMAP);
  }
  const ::flatbuffers::String *OrmMap() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ORMMAP);
  }
  const ::flatbuffers::String *EmissiveMap() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EMISSIVEMAP);
  }
  asdx::res::AlphaType AlphaMode() const {
    return static_cast<asdx::res::AlphaType>(GetField<uint8_t>(VT_ALPHAMODE, 0));
  }
  float AlphaCutOff() const {
    return GetField<float>(VT_ALPHACUTOFF, 0.0f);
  }
  bool TwoSided() const {
    return GetField<uint8_t>(VT_TWOSIDED, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyField<asdx::res::Float3>(verifier, VT_BASECOLORFACTOR, 4) &&
           VerifyField<float>(verifier, VT_ALPHA, 4) &&
           VerifyField<float>(verifier, VT_OCCLUSIONFACTOR, 4) &&
           VerifyField<float>(verifier, VT_ROUGHNESSFACTOR, 4) &&
           VerifyField<float>(verifier, VT_METALNESSFACTOR, 4) &&
           VerifyField<float>(verifier, VT_IOR, 4) &&
           VerifyField<asdx::res::Float3>(verifier, VT_EMISSIVEFACTOR, 4) &&
           VerifyOffset(verifier, VT_BASECOLORMAP) &&
           verifier.VerifyString(BaseColorMap()) &&
           VerifyOffset(verifier, VT_NORMALMAP) &&
           verifier.VerifyString(NormalMap()) &&
           VerifyOffset(verifier, VT_ORMMAP) &&
           verifier.VerifyString(OrmMap()) &&
           VerifyOffset(verifier, VT_EMISSIVEMAP) &&
           verifier.VerifyString(EmissiveMap()) &&
           VerifyField<uint8_t>(verifier, VT_ALPHAMODE, 1) &&
           VerifyField<float>(verifier, VT_ALPHACUTOFF, 4) &&
           VerifyField<uint8_t>(verifier, VT_TWOSIDED, 1) &&
           verifier.EndTable();
  }
};

struct MaterialBuilder {
  typedef Material Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(Material::VT_NAME, Name);
  }
  void add_BaseColorFactor(const asdx::res::Float3 *BaseColorFactor) {
    fbb_.AddStruct(Material::VT_BASECOLORFACTOR, BaseColorFactor);
  }
  void add_Alpha(float Alpha) {
    fbb_.AddElement<float>(Material::VT_ALPHA, Alpha, 0.0f);
  }
  void add_OcclusionFactor(float OcclusionFactor) {
    fbb_.AddElement<float>(Material::VT_OCCLUSIONFACTOR, OcclusionFactor, 0.0f);
  }
  void add_RoughnessFactor(float RoughnessFactor) {
    fbb_.AddElement<float>(Material::VT_ROUGHNESSFACTOR, RoughnessFactor, 0.0f);
  }
  void add_MetalnessFactor(float MetalnessFactor) {
    fbb_.AddElement<float>(Material::VT_METALNESSFACTOR, MetalnessFactor, 0.0f);
  }
  void add_Ior(float Ior) {
    fbb_.AddElement<float>(Material::VT_IOR, Ior, 0.0f);
  }
  void add_EmissiveFactor(const asdx::res::Float3 *EmissiveFactor) {
    fbb_.AddStruct(Material::VT_EMISSIVEFACTOR, EmissiveFactor);
  }
  void add_BaseColorMap(::flatbuffers::Offset<::flatbuffers::String> BaseColorMap) {
    fbb_.AddOffset(Material::VT_BASECOLORMAP, BaseColorMap);
  }
  void add_NormalMap(::flatbuffers::Offset<::flatbuffers::String> NormalMap) {
    fbb_.AddOffset(Material::VT_NORMALMAP, NormalMap);
  }
  void add_OrmMap(::flatbuffers::Offset<::flatbuffers::String> OrmMap) {
    fbb_.AddOffset(Material::VT_ORMMAP, OrmMap);
  }
  void add_EmissiveMap(::flatbuffers::Offset<::flatbuffers::String> EmissiveMap) {
    fbb_.AddOffset(Material::VT_EMISSIVEMAP, EmissiveMap);
  }
  void add_AlphaMode(asdx::res::AlphaType AlphaMode) {
    fbb_.AddElement<uint8_t>(Material::VT_ALPHAMODE, static_cast<uint8_t>(AlphaMode), 0);
  }
  void add_AlphaCutOff(float AlphaCutOff) {
    fbb_.AddElement<float>(Material::VT_ALPHACUTOFF, AlphaCutOff, 0.0f);
  }
  void add_TwoSided(bool TwoSided) {
    fbb_.AddElement<uint8_t>(Material::VT_TWOSIDED, static_cast<uint8_t>(TwoSided), 0);
  }
  explicit MaterialBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Material> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Material>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Material> CreateMaterial(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    const asdx::res::Float3 *BaseColorFactor = nullptr,
    float Alpha = 0.0f,
    float OcclusionFactor = 0.0f,
    float RoughnessFactor = 0.0f,
    float MetalnessFactor = 0.0f,
    float Ior = 0.0f,
    const asdx::res::Float3 *EmissiveFactor = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> BaseColorMap = 0,
    ::flatbuffers::Offset<::flatbuffers::String> NormalMap = 0,
    ::flatbuffers::Offset<::flatbuffers::String> OrmMap = 0,
    ::flatbuffers::Offset<::flatbuffers::String> EmissiveMap = 0,
    asdx::res::AlphaType AlphaMode = asdx::res::AlphaType_Opaque,
    float AlphaCutOff = 0.0f,
    bool TwoSided = false) {
  MaterialBuilder builder_(_fbb);
  builder_.add_AlphaCutOff(AlphaCutOff);
  builder_.add_EmissiveMap(EmissiveMap);
  builder_.add_OrmMap(OrmMap);
  builder_.add_NormalMap(NormalMap);
  builder_.add_BaseColorMap(BaseColorMap);
  builder_.add_EmissiveFactor(EmissiveFactor);
  builder_.add_Ior(Ior);
  builder_.add_MetalnessFactor(MetalnessFactor);
  builder_.add_RoughnessFactor(RoughnessFactor);
  builder_.add_OcclusionFactor(OcclusionFactor);
  builder_.add_Alpha(Alpha);
  builder_.add_BaseColorFactor(BaseColorFactor);
  builder_.add_Name(Name);
  builder_.add_TwoSided(TwoSided);
  builder_.add_AlphaMode(AlphaMode);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Material> CreateMaterialDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    const asdx::res::Float3 *BaseColorFactor = nullptr,
    float Alpha = 0.0f,
    float OcclusionFactor = 0.0f,
    float RoughnessFactor = 0.0f,
    float MetalnessFactor = 0.0f,
    float Ior = 0.0f,
    const asdx::res::Float3 *EmissiveFactor = nullptr,
    const char *BaseColorMap = nullptr,
    const char *NormalMap = nullptr,
    const char *OrmMap = nullptr,
    const char *EmissiveMap = nullptr,
    asdx::res::AlphaType AlphaMode = asdx::res::AlphaType_Opaque,
    float AlphaCutOff = 0.0f,
    bool TwoSided = false) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto BaseColorMap__ = BaseColorMap ? _fbb.CreateString(BaseColorMap) : 0;
  auto NormalMap__ = NormalMap ? _fbb.CreateString(NormalMap) : 0;
  auto OrmMap__ = OrmMap ? _fbb.CreateString(OrmMap) : 0;
  auto EmissiveMap__ = EmissiveMap ? _fbb.CreateString(EmissiveMap) : 0;
  return asdx::res::CreateMaterial(
      _fbb,
      Name__,
      BaseColorFactor,
      Alpha,
      OcclusionFactor,
      RoughnessFactor,
      MetalnessFactor,
      Ior,
      EmissiveFactor,
      BaseColorMap__,
      NormalMap__,
      OrmMap__,
      EmissiveMap__,
      AlphaMode,
      AlphaCutOff,
      TwoSided);
}

struct ModelBatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelBatchBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAMES = 4,
    VT_TRANSFORMS = 6,
    VT_MESHES = 8,
    VT_BOUNDSPHERE = 10,
    VT_BOUNDBOX = 12
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *Names() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_NAMES);
  }
  const ::flatbuffers::Vector<const asdx::res::Float3x4 *> *Transforms() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::Float3x4 *> *>(VT_TRANSFORMS);
  }
  const ::flatbuffers::Vector<uint32_t> *Meshes() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_MESHES);
  }
  const asdx::res::BoundingSphere *BoundSphere() const {
    return GetStruct<const asdx::res::BoundingSphere *>(VT_BOUNDSPHERE);
  }
  const asdx::res::BoundingBox *BoundBox() const {
    return GetStruct<const asdx::res::BoundingBox *>(VT_BOUNDBOX);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAMES) &&
           verifier.VerifyVector(Names()) &&
           verifier.VerifyVectorOfStrings(Names()) &&
           VerifyOffset(verifier, VT_TRANSFORMS) &&
           verifier.VerifyVector(Transforms()) &&
           VerifyOffset(verifier, VT_MESHES) &&
           verifier.VerifyVector(Meshes()) &&
           VerifyField<asdx::res::BoundingSphere>(verifier, VT_BOUNDSPHERE, 4) &&
           VerifyField<asdx::res::BoundingBox>(verifier, VT_BOUNDBOX, 4) &&
           verifier.EndTable();
  }
};

struct ModelBatchBuilder {
  typedef ModelBatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Names(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> Names) {
    fbb_.AddOffset(ModelBatch::VT_NAMES, Names);
  }
  void add_Transforms(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3x4 *>> Transforms) {
    fbb_.AddOffset(ModelBatch::VT_TRANSFORMS, Transforms);
  }
  void add_Meshes(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> Meshes) {
    fbb_.AddOffset(ModelBatch::VT_MESHES, Meshes);
  }
  void add_BoundSphere(const asdx::res::BoundingSphere *BoundSphere) {
    fbb_.AddStruct(ModelBatch::VT_BOUNDSPHERE, BoundSphere);
  }
  void add_BoundBox(const asdx::res::BoundingBox *BoundBox) {
    fbb_.AddStruct(ModelBatch::VT_BOUNDBOX, BoundBox);
  }
  explicit ModelBatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelBatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelBatch>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelBatch> CreateModelBatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> Names = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::Float3x4 *>> Transforms = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> Meshes = 0,
    const asdx::res::BoundingSphere *BoundSphere = nullptr,
    const asdx::res::BoundingBox *BoundBox = nullptr) {
  ModelBatchBuilder builder_(_fbb);
  builder_.add_BoundBox(BoundBox);
  builder_.add_BoundSphere(BoundSphere);
  builder_.add_Meshes(Meshes);
  builder_.add_Transforms(Transforms);
  builder_.add_Names(Names);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModelBatch> CreateModelBatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *Names = nullptr,
    const std::vector<asdx::res::Float3x4> *Transforms = nullptr,
    const std::vector<uint32_t> *Meshes = nullptr,
    const asdx::res::BoundingSphere *BoundSphere = nullptr,
    const asdx::res::BoundingBox *BoundBox = nullptr) {
  auto Names__ = Names ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*Names) : 0;
  auto Transforms__ = Transforms ? _fbb.CreateVectorOfStructs<asdx::res::Float3x4>(*Transforms) : 0;
  auto Meshes__ = Meshes ? _fbb.CreateVector<uint32_t>(*Meshes) : 0;
  return asdx::res::CreateModelBatch(
      _fbb,
      Names__,
      Transforms__,
      Meshes__,
      BoundSphere,
      BoundBox);
}

struct ModelBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_MESHES = 6,
    VT_MATERIALS = 8,
    VT_BONES = 10,
    VT_BATCHES = 12,
    VT_BOUNDSPHERE = 14,
    VT_BOUNDBOX = 16,
    VT_TOTALINSTANCECOUNT = 18,
    VT_ROOTTRANSFORM = 20,
    VT_INVROOTTRANSFORM = 22
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Mesh>> *Meshes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Mesh>> *>(VT_MESHES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Material>> *Materials() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Material>> *>(VT_MATERIALS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Bone>> *Bones() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Bone>> *>(VT_BONES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::ModelBatch>> *Batches() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::ModelBatch>> *>(VT_BATCHES);
  }
  const asdx::res::BoundingSphere *BoundSphere() const {
    return GetStruct<const asdx::res::BoundingSphere *>(VT_BOUNDSPHERE);
  }
  const asdx::res::BoundingBox *BoundBox() const {
    return GetStruct<const asdx::res::BoundingBox *>(VT_BOUNDBOX);
  }
  uint64_t TotalInstanceCount() const {
    return GetField<uint64_t>(VT_TOTALINSTANCECOUNT, 0);
  }
  const asdx::res::Float3x4 *RootTransform() const {
    return GetStruct<const asdx::res::Float3x4 *>(VT_ROOTTRANSFORM);
  }
  const asdx::res::Float3x4 *InvRootTransform() const {
    return GetStruct<const asdx::res::Float3x4 *>(VT_INVROOTTRANSFORM);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_MESHES) &&
           verifier.VerifyVector(Meshes()) &&
           verifier.VerifyVectorOfTables(Meshes()) &&
           VerifyOffset(verifier, VT_MATERIALS) &&
           verifier.VerifyVector(Materials()) &&
           verifier.VerifyVectorOfTables(Materials()) &&
           VerifyOffset(verifier, VT_BONES) &&
           verifier.VerifyVector(Bones()) &&
           verifier.VerifyVectorOfTables(Bones()) &&
           VerifyOffset(verifier, VT_BATCHES) &&
           verifier.VerifyVector(Batches()) &&
           verifier.VerifyVectorOfTables(Batches()) &&
           VerifyField<asdx::res::BoundingSphere>(verifier, VT_BOUNDSPHERE, 4) &&
           VerifyField<asdx::res::BoundingBox>(verifier, VT_BOUNDBOX, 4) &&
           VerifyField<uint64_t>(verifier, VT_TOTALINSTANCECOUNT, 8) &&
           VerifyField<asdx::res::Float3x4>(verifier, VT_ROOTTRANSFORM, 4) &&
           VerifyField<asdx::res::Float3x4>(verifier, VT_INVROOTTRANSFORM, 4) &&
           verifier.EndTable();
  }
};

struct ModelBinaryBuilder {
  typedef ModelBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(ModelBinary::VT_VERSION, Version, 0);
  }
  void add_Meshes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Mesh>>> Meshes) {
    fbb_.AddOffset(ModelBinary::VT_MESHES, Meshes);
  }
  void add_Materials(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Material>>> Materials) {
    fbb_.AddOffset(ModelBinary::VT_MATERIALS, Materials);
  }
  void add_Bones(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Bone>>> Bones) {
    fbb_.AddOffset(ModelBinary::VT_BONES, Bones);
  }
  void add_Batches(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::ModelBatch>>> Batches) {
    fbb_.AddOffset(ModelBinary::VT_BATCHES, Batches);
  }
  void add_BoundSphere(const asdx::res::BoundingSphere *BoundSphere) {
    fbb_.AddStruct(ModelBinary::VT_BOUNDSPHERE, BoundSphere);
  }
  void add_BoundBox(const asdx::res::BoundingBox *BoundBox) {
    fbb_.AddStruct(ModelBinary::VT_BOUNDBOX, BoundBox);
  }
  void add_TotalInstanceCount(uint64_t TotalInstanceCount) {
    fbb_.AddElement<uint64_t>(ModelBinary::VT_TOTALINSTANCECOUNT, TotalInstanceCount, 0);
  }
  void add_RootTransform(const asdx::res::Float3x4 *RootTransform) {
    fbb_.AddStruct(ModelBinary::VT_ROOTTRANSFORM, RootTransform);
  }
  void add_InvRootTransform(const asdx::res::Float3x4 *InvRootTransform) {
    fbb_.AddStruct(ModelBinary::VT_INVROOTTRANSFORM, InvRootTransform);
  }
  explicit ModelBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelBinary> CreateModelBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Mesh>>> Meshes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Material>>> Materials = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::Bone>>> Bones = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::ModelBatch>>> Batches = 0,
    const asdx::res::BoundingSphere *BoundSphere = nullptr,
    const asdx::res::BoundingBox *BoundBox = nullptr,
    uint64_t TotalInstanceCount = 0,
    const asdx::res::Float3x4 *RootTransform = nullptr,
    const asdx::res::Float3x4 *InvRootTransform = nullptr) {
  ModelBinaryBuilder builder_(_fbb);
  builder_.add_TotalInstanceCount(TotalInstanceCount);
  builder_.add_InvRootTransform(InvRootTransform);
  builder_.add_RootTransform(RootTransform);
  builder_.add_BoundBox(BoundBox);
  builder_.add_BoundSphere(BoundSphere);
  builder_.add_Batches(Batches);
  builder_.add_Bones(Bones);
  builder_.add_Materials(Materials);
  builder_.add_Meshes(Meshes);
  builder_.add_Version(Version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModelBinary> CreateModelBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    const std::vector<::flatbuffers::Offset<asdx::res::Mesh>> *Meshes = nullptr,
    const std::vector<::flatbuffers::Offset<asdx::res::Material>> *Materials = nullptr,
    const std::vector<::flatbuffers::Offset<asdx::res::Bone>> *Bones = nullptr,
    const std::vector<::flatbuffers::Offset<asdx::res::ModelBatch>> *Batches = nullptr,
    const asdx::res::BoundingSphere *BoundSphere = nullptr,
    const asdx::res::BoundingBox *BoundBox = nullptr,
    uint64_t TotalInstanceCount = 0,
    const asdx::res::Float3x4 *RootTransform = nullptr,
    const asdx::res::Float3x4 *InvRootTransform = nullptr) {
  auto Meshes__ = Meshes ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::Mesh>>(*Meshes) : 0;
  auto Materials__ = Materials ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::Material>>(*Materials) : 0;
  auto Bones__ = Bones ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::Bone>>(*Bones) : 0;
  auto Batches__ = Batches ? _fbb.CreateVector<::flatbuffers::Offset<asdx::res::ModelBatch>>(*Batches) : 0;
  return asdx::res::CreateModelBinary(
      _fbb,
      Version,
      Meshes__,
      Materials__,
      Bones__,
      Batches__,
      BoundSphere,
      BoundBox,
      TotalInstanceCount,
      RootTransform,
      InvRootTransform);
}

inline const asdx::res::ModelBinary *GetModelBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::ModelBinary>(buf);
}

inline const asdx::res::ModelBinary *GetSizePrefixedModelBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::ModelBinary>(buf);
}

inline bool VerifyModelBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::ModelBinary>(nullptr);
}

inline bool VerifySizePrefixedModelBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::ModelBinary>(nullptr);
}

inline void FinishModelBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::ModelBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedModelBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::ModelBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_MODELBINARY_ASDX_RES_H_
