// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOTIONBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_MOTIONBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "ResTypes_generated.h"

namespace asdx {
namespace res {

struct KeyFloat3;

struct KeyQuaternion;

struct BoneAnimation;
struct BoneAnimationBuilder;

struct MotionClip;
struct MotionClipBuilder;

struct MotionBinary;
struct MotionBinaryBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) KeyFloat3 FLATBUFFERS_FINAL_CLASS {
 private:
  float Time_;
  asdx::res::Float3 Value_;

 public:
  KeyFloat3()
      : Time_(0),
        Value_() {
  }
  KeyFloat3(float _Time, const asdx::res::Float3 &_Value)
      : Time_(::flatbuffers::EndianScalar(_Time)),
        Value_(_Value) {
  }
  float Time() const {
    return ::flatbuffers::EndianScalar(Time_);
  }
  bool KeyCompareLessThan(const KeyFloat3 * const o) const {
    return Time() < o->Time();
  }
  int KeyCompareWithValue(float _Time) const {
    return static_cast<int>(Time() > _Time) - static_cast<int>(Time() < _Time);
  }
  const asdx::res::Float3 &Value() const {
    return Value_;
  }
};
FLATBUFFERS_STRUCT_END(KeyFloat3, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) KeyQuaternion FLATBUFFERS_FINAL_CLASS {
 private:
  float Time_;
  asdx::res::Float4 Value_;

 public:
  KeyQuaternion()
      : Time_(0),
        Value_() {
  }
  KeyQuaternion(float _Time, const asdx::res::Float4 &_Value)
      : Time_(::flatbuffers::EndianScalar(_Time)),
        Value_(_Value) {
  }
  float Time() const {
    return ::flatbuffers::EndianScalar(Time_);
  }
  bool KeyCompareLessThan(const KeyQuaternion * const o) const {
    return Time() < o->Time();
  }
  int KeyCompareWithValue(float _Time) const {
    return static_cast<int>(Time() > _Time) - static_cast<int>(Time() < _Time);
  }
  const asdx::res::Float4 &Value() const {
    return Value_;
  }
};
FLATBUFFERS_STRUCT_END(KeyQuaternion, 20);

struct BoneAnimation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoneAnimationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BONENAME = 4,
    VT_POSITIONS = 6,
    VT_ROTATIONS = 8,
    VT_SCALINGS = 10
  };
  const ::flatbuffers::String *BoneName() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BONENAME);
  }
  bool KeyCompareLessThan(const BoneAnimation * const o) const {
    return *BoneName() < *o->BoneName();
  }
  int KeyCompareWithValue(const char *_BoneName) const {
    return strcmp(BoneName()->c_str(), _BoneName);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _BoneName) const {
    if (BoneName()->c_str() < _BoneName) return -1;
    if (_BoneName < BoneName()->c_str()) return 1;
    return 0;
  }
  const ::flatbuffers::Vector<const asdx::res::KeyFloat3 *> *Positions() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::KeyFloat3 *> *>(VT_POSITIONS);
  }
  const ::flatbuffers::Vector<const asdx::res::KeyQuaternion *> *Rotations() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::KeyQuaternion *> *>(VT_ROTATIONS);
  }
  const ::flatbuffers::Vector<const asdx::res::KeyFloat3 *> *Scalings() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::KeyFloat3 *> *>(VT_SCALINGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BONENAME) &&
           verifier.VerifyString(BoneName()) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(Positions()) &&
           VerifyOffset(verifier, VT_ROTATIONS) &&
           verifier.VerifyVector(Rotations()) &&
           VerifyOffset(verifier, VT_SCALINGS) &&
           verifier.VerifyVector(Scalings()) &&
           verifier.EndTable();
  }
};

struct BoneAnimationBuilder {
  typedef BoneAnimation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_BoneName(::flatbuffers::Offset<::flatbuffers::String> BoneName) {
    fbb_.AddOffset(BoneAnimation::VT_BONENAME, BoneName);
  }
  void add_Positions(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyFloat3 *>> Positions) {
    fbb_.AddOffset(BoneAnimation::VT_POSITIONS, Positions);
  }
  void add_Rotations(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyQuaternion *>> Rotations) {
    fbb_.AddOffset(BoneAnimation::VT_ROTATIONS, Rotations);
  }
  void add_Scalings(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyFloat3 *>> Scalings) {
    fbb_.AddOffset(BoneAnimation::VT_SCALINGS, Scalings);
  }
  explicit BoneAnimationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BoneAnimation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BoneAnimation>(end);
    fbb_.Required(o, BoneAnimation::VT_BONENAME);
    return o;
  }
};

inline ::flatbuffers::Offset<BoneAnimation> CreateBoneAnimation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> BoneName = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyFloat3 *>> Positions = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyQuaternion *>> Rotations = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyFloat3 *>> Scalings = 0) {
  BoneAnimationBuilder builder_(_fbb);
  builder_.add_Scalings(Scalings);
  builder_.add_Rotations(Rotations);
  builder_.add_Positions(Positions);
  builder_.add_BoneName(BoneName);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BoneAnimation> CreateBoneAnimationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *BoneName = nullptr,
    std::vector<asdx::res::KeyFloat3> *Positions = nullptr,
    std::vector<asdx::res::KeyQuaternion> *Rotations = nullptr,
    std::vector<asdx::res::KeyFloat3> *Scalings = nullptr) {
  auto BoneName__ = BoneName ? _fbb.CreateString(BoneName) : 0;
  auto Positions__ = Positions ? _fbb.CreateVectorOfSortedStructs<asdx::res::KeyFloat3>(Positions) : 0;
  auto Rotations__ = Rotations ? _fbb.CreateVectorOfSortedStructs<asdx::res::KeyQuaternion>(Rotations) : 0;
  auto Scalings__ = Scalings ? _fbb.CreateVectorOfSortedStructs<asdx::res::KeyFloat3>(Scalings) : 0;
  return asdx::res::CreateBoneAnimation(
      _fbb,
      BoneName__,
      Positions__,
      Rotations__,
      Scalings__);
}

struct MotionClip FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MotionClipBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DURATION = 6,
    VT_TICKSPERSECOND = 8,
    VT_BONES = 10
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool KeyCompareLessThan(const MotionClip * const o) const {
    return *Name() < *o->Name();
  }
  int KeyCompareWithValue(const char *_Name) const {
    return strcmp(Name()->c_str(), _Name);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _Name) const {
    if (Name()->c_str() < _Name) return -1;
    if (_Name < Name()->c_str()) return 1;
    return 0;
  }
  float Duration() const {
    return GetField<float>(VT_DURATION, 0.0f);
  }
  float TicksPerSecond() const {
    return GetField<float>(VT_TICKSPERSECOND, 0.0f);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::BoneAnimation>> *Bones() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::BoneAnimation>> *>(VT_BONES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyField<float>(verifier, VT_DURATION, 4) &&
           VerifyField<float>(verifier, VT_TICKSPERSECOND, 4) &&
           VerifyOffset(verifier, VT_BONES) &&
           verifier.VerifyVector(Bones()) &&
           verifier.VerifyVectorOfTables(Bones()) &&
           verifier.EndTable();
  }
};

struct MotionClipBuilder {
  typedef MotionClip Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(MotionClip::VT_NAME, Name);
  }
  void add_Duration(float Duration) {
    fbb_.AddElement<float>(MotionClip::VT_DURATION, Duration, 0.0f);
  }
  void add_TicksPerSecond(float TicksPerSecond) {
    fbb_.AddElement<float>(MotionClip::VT_TICKSPERSECOND, TicksPerSecond, 0.0f);
  }
  void add_Bones(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::BoneAnimation>>> Bones) {
    fbb_.AddOffset(MotionClip::VT_BONES, Bones);
  }
  explicit MotionClipBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MotionClip> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MotionClip>(end);
    fbb_.Required(o, MotionClip::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<MotionClip> CreateMotionClip(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    float Duration = 0.0f,
    float TicksPerSecond = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::BoneAnimation>>> Bones = 0) {
  MotionClipBuilder builder_(_fbb);
  builder_.add_Bones(Bones);
  builder_.add_TicksPerSecond(TicksPerSecond);
  builder_.add_Duration(Duration);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MotionClip> CreateMotionClipDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    float Duration = 0.0f,
    float TicksPerSecond = 0.0f,
    std::vector<::flatbuffers::Offset<asdx::res::BoneAnimation>> *Bones = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Bones__ = Bones ? _fbb.CreateVectorOfSortedTables<asdx::res::BoneAnimation>(Bones) : 0;
  return asdx::res::CreateMotionClip(
      _fbb,
      Name__,
      Duration,
      TicksPerSecond,
      Bones__);
}

struct MotionBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MotionBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_CLIPS = 6
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionClip>> *Clips() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionClip>> *>(VT_CLIPS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_CLIPS) &&
           verifier.VerifyVector(Clips()) &&
           verifier.VerifyVectorOfTables(Clips()) &&
           verifier.EndTable();
  }
};

struct MotionBinaryBuilder {
  typedef MotionBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(MotionBinary::VT_VERSION, Version, 0);
  }
  void add_Clips(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionClip>>> Clips) {
    fbb_.AddOffset(MotionBinary::VT_CLIPS, Clips);
  }
  explicit MotionBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MotionBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MotionBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MotionBinary> CreateMotionBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionClip>>> Clips = 0) {
  MotionBinaryBuilder builder_(_fbb);
  builder_.add_Clips(Clips);
  builder_.add_Version(Version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MotionBinary> CreateMotionBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    std::vector<::flatbuffers::Offset<asdx::res::MotionClip>> *Clips = nullptr) {
  auto Clips__ = Clips ? _fbb.CreateVectorOfSortedTables<asdx::res::MotionClip>(Clips) : 0;
  return asdx::res::CreateMotionBinary(
      _fbb,
      Version,
      Clips__);
}

inline const asdx::res::MotionBinary *GetMotionBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::MotionBinary>(buf);
}

inline const asdx::res::MotionBinary *GetSizePrefixedMotionBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::MotionBinary>(buf);
}

inline bool VerifyMotionBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::MotionBinary>(nullptr);
}

inline bool VerifySizePrefixedMotionBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::MotionBinary>(nullptr);
}

inline void FinishMotionBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MotionBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMotionBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MotionBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_MOTIONBINARY_ASDX_RES_H_
