// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOTIONBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_MOTIONBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "ResTypes_generated.h"

namespace asdx {
namespace res {

struct KeyFloat3;

struct KeyQuaternion;

struct MotionTrack;
struct MotionTrackBuilder;

struct MotionClip;
struct MotionClipBuilder;

struct MotionBinary;
struct MotionBinaryBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) KeyFloat3 FLATBUFFERS_FINAL_CLASS {
 private:
  float Time_;
  asdx::res::Float3 Value_;

 public:
  KeyFloat3()
      : Time_(0),
        Value_() {
  }
  KeyFloat3(float _Time, const asdx::res::Float3 &_Value)
      : Time_(::flatbuffers::EndianScalar(_Time)),
        Value_(_Value) {
  }
  float Time() const {
    return ::flatbuffers::EndianScalar(Time_);
  }
  bool KeyCompareLessThan(const KeyFloat3 * const o) const {
    return Time() < o->Time();
  }
  int KeyCompareWithValue(float _Time) const {
    return static_cast<int>(Time() > _Time) - static_cast<int>(Time() < _Time);
  }
  const asdx::res::Float3 &Value() const {
    return Value_;
  }
};
FLATBUFFERS_STRUCT_END(KeyFloat3, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) KeyQuaternion FLATBUFFERS_FINAL_CLASS {
 private:
  float Time_;
  asdx::res::Quaternion Value_;

 public:
  KeyQuaternion()
      : Time_(0),
        Value_() {
  }
  KeyQuaternion(float _Time, const asdx::res::Quaternion &_Value)
      : Time_(::flatbuffers::EndianScalar(_Time)),
        Value_(_Value) {
  }
  float Time() const {
    return ::flatbuffers::EndianScalar(Time_);
  }
  bool KeyCompareLessThan(const KeyQuaternion * const o) const {
    return Time() < o->Time();
  }
  int KeyCompareWithValue(float _Time) const {
    return static_cast<int>(Time() > _Time) - static_cast<int>(Time() < _Time);
  }
  const asdx::res::Quaternion &Value() const {
    return Value_;
  }
};
FLATBUFFERS_STRUCT_END(KeyQuaternion, 20);

struct MotionTrack FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MotionTrackBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_POSITIONS = 6,
    VT_ROTATIONS = 8,
    VT_SCALINGS = 10
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool KeyCompareLessThan(const MotionTrack * const o) const {
    return *Name() < *o->Name();
  }
  int KeyCompareWithValue(const char *_Name) const {
    return strcmp(Name()->c_str(), _Name);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _Name) const {
    if (Name()->c_str() < _Name) return -1;
    if (_Name < Name()->c_str()) return 1;
    return 0;
  }
  const ::flatbuffers::Vector<const asdx::res::KeyFloat3 *> *Positions() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::KeyFloat3 *> *>(VT_POSITIONS);
  }
  const ::flatbuffers::Vector<const asdx::res::KeyQuaternion *> *Rotations() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::KeyQuaternion *> *>(VT_ROTATIONS);
  }
  const ::flatbuffers::Vector<const asdx::res::KeyFloat3 *> *Scalings() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::KeyFloat3 *> *>(VT_SCALINGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(Positions()) &&
           VerifyOffset(verifier, VT_ROTATIONS) &&
           verifier.VerifyVector(Rotations()) &&
           VerifyOffset(verifier, VT_SCALINGS) &&
           verifier.VerifyVector(Scalings()) &&
           verifier.EndTable();
  }
};

struct MotionTrackBuilder {
  typedef MotionTrack Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(MotionTrack::VT_NAME, Name);
  }
  void add_Positions(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyFloat3 *>> Positions) {
    fbb_.AddOffset(MotionTrack::VT_POSITIONS, Positions);
  }
  void add_Rotations(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyQuaternion *>> Rotations) {
    fbb_.AddOffset(MotionTrack::VT_ROTATIONS, Rotations);
  }
  void add_Scalings(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyFloat3 *>> Scalings) {
    fbb_.AddOffset(MotionTrack::VT_SCALINGS, Scalings);
  }
  explicit MotionTrackBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MotionTrack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MotionTrack>(end);
    fbb_.Required(o, MotionTrack::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<MotionTrack> CreateMotionTrack(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyFloat3 *>> Positions = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyQuaternion *>> Rotations = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::KeyFloat3 *>> Scalings = 0) {
  MotionTrackBuilder builder_(_fbb);
  builder_.add_Scalings(Scalings);
  builder_.add_Rotations(Rotations);
  builder_.add_Positions(Positions);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MotionTrack> CreateMotionTrackDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    std::vector<asdx::res::KeyFloat3> *Positions = nullptr,
    std::vector<asdx::res::KeyQuaternion> *Rotations = nullptr,
    std::vector<asdx::res::KeyFloat3> *Scalings = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Positions__ = Positions ? _fbb.CreateVectorOfSortedStructs<asdx::res::KeyFloat3>(Positions) : 0;
  auto Rotations__ = Rotations ? _fbb.CreateVectorOfSortedStructs<asdx::res::KeyQuaternion>(Rotations) : 0;
  auto Scalings__ = Scalings ? _fbb.CreateVectorOfSortedStructs<asdx::res::KeyFloat3>(Scalings) : 0;
  return asdx::res::CreateMotionTrack(
      _fbb,
      Name__,
      Positions__,
      Rotations__,
      Scalings__);
}

struct MotionClip FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MotionClipBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DURATION = 6,
    VT_TICKSPERSECOND = 8,
    VT_TRACKS = 10
  };
  const ::flatbuffers::String *Name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool KeyCompareLessThan(const MotionClip * const o) const {
    return *Name() < *o->Name();
  }
  int KeyCompareWithValue(const char *_Name) const {
    return strcmp(Name()->c_str(), _Name);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _Name) const {
    if (Name()->c_str() < _Name) return -1;
    if (_Name < Name()->c_str()) return 1;
    return 0;
  }
  float Duration() const {
    return GetField<float>(VT_DURATION, 0.0f);
  }
  float TicksPerSecond() const {
    return GetField<float>(VT_TICKSPERSECOND, 0.0f);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionTrack>> *Tracks() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionTrack>> *>(VT_TRACKS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(Name()) &&
           VerifyField<float>(verifier, VT_DURATION, 4) &&
           VerifyField<float>(verifier, VT_TICKSPERSECOND, 4) &&
           VerifyOffset(verifier, VT_TRACKS) &&
           verifier.VerifyVector(Tracks()) &&
           verifier.VerifyVectorOfTables(Tracks()) &&
           verifier.EndTable();
  }
};

struct MotionClipBuilder {
  typedef MotionClip Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Name(::flatbuffers::Offset<::flatbuffers::String> Name) {
    fbb_.AddOffset(MotionClip::VT_NAME, Name);
  }
  void add_Duration(float Duration) {
    fbb_.AddElement<float>(MotionClip::VT_DURATION, Duration, 0.0f);
  }
  void add_TicksPerSecond(float TicksPerSecond) {
    fbb_.AddElement<float>(MotionClip::VT_TICKSPERSECOND, TicksPerSecond, 0.0f);
  }
  void add_Tracks(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionTrack>>> Tracks) {
    fbb_.AddOffset(MotionClip::VT_TRACKS, Tracks);
  }
  explicit MotionClipBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MotionClip> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MotionClip>(end);
    fbb_.Required(o, MotionClip::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<MotionClip> CreateMotionClip(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> Name = 0,
    float Duration = 0.0f,
    float TicksPerSecond = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionTrack>>> Tracks = 0) {
  MotionClipBuilder builder_(_fbb);
  builder_.add_Tracks(Tracks);
  builder_.add_TicksPerSecond(TicksPerSecond);
  builder_.add_Duration(Duration);
  builder_.add_Name(Name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MotionClip> CreateMotionClipDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *Name = nullptr,
    float Duration = 0.0f,
    float TicksPerSecond = 0.0f,
    std::vector<::flatbuffers::Offset<asdx::res::MotionTrack>> *Tracks = nullptr) {
  auto Name__ = Name ? _fbb.CreateString(Name) : 0;
  auto Tracks__ = Tracks ? _fbb.CreateVectorOfSortedTables<asdx::res::MotionTrack>(Tracks) : 0;
  return asdx::res::CreateMotionClip(
      _fbb,
      Name__,
      Duration,
      TicksPerSecond,
      Tracks__);
}

struct MotionBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MotionBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_ROOTTRANSFORM = 6,
    VT_CLIPS = 8
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const asdx::res::Float4x4 *RootTransform() const {
    return GetStruct<const asdx::res::Float4x4 *>(VT_ROOTTRANSFORM);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionClip>> *Clips() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionClip>> *>(VT_CLIPS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<asdx::res::Float4x4>(verifier, VT_ROOTTRANSFORM, 4) &&
           VerifyOffset(verifier, VT_CLIPS) &&
           verifier.VerifyVector(Clips()) &&
           verifier.VerifyVectorOfTables(Clips()) &&
           verifier.EndTable();
  }
};

struct MotionBinaryBuilder {
  typedef MotionBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(MotionBinary::VT_VERSION, Version, 0);
  }
  void add_RootTransform(const asdx::res::Float4x4 *RootTransform) {
    fbb_.AddStruct(MotionBinary::VT_ROOTTRANSFORM, RootTransform);
  }
  void add_Clips(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionClip>>> Clips) {
    fbb_.AddOffset(MotionBinary::VT_CLIPS, Clips);
  }
  explicit MotionBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MotionBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MotionBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MotionBinary> CreateMotionBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    const asdx::res::Float4x4 *RootTransform = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<asdx::res::MotionClip>>> Clips = 0) {
  MotionBinaryBuilder builder_(_fbb);
  builder_.add_Clips(Clips);
  builder_.add_RootTransform(RootTransform);
  builder_.add_Version(Version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MotionBinary> CreateMotionBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    const asdx::res::Float4x4 *RootTransform = nullptr,
    std::vector<::flatbuffers::Offset<asdx::res::MotionClip>> *Clips = nullptr) {
  auto Clips__ = Clips ? _fbb.CreateVectorOfSortedTables<asdx::res::MotionClip>(Clips) : 0;
  return asdx::res::CreateMotionBinary(
      _fbb,
      Version,
      RootTransform,
      Clips__);
}

inline const asdx::res::MotionBinary *GetMotionBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::MotionBinary>(buf);
}

inline const asdx::res::MotionBinary *GetSizePrefixedMotionBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::MotionBinary>(buf);
}

inline bool VerifyMotionBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::MotionBinary>(nullptr);
}

inline bool VerifySizePrefixedMotionBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::MotionBinary>(nullptr);
}

inline void FinishMotionBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MotionBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMotionBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::MotionBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_MOTIONBINARY_ASDX_RES_H_
