// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RESTYPES_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_RESTYPES_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace asdx {
namespace res {

struct Float2;

struct Float3;

struct Float4;

struct Int2;

struct Int3;

struct Int4;

struct Uint2;

struct Uint3;

struct Uint4;

struct Unorm2;

struct Unorm3;

struct Unorm4;

struct Float3x4;

struct Float4x4;

struct BoundingBox;

struct BoundingSphere;

struct Range;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float2 FLATBUFFERS_FINAL_CLASS {
 private:
  float X_;
  float Y_;

 public:
  Float2()
      : X_(0),
        Y_(0) {
  }
  Float2(float _X, float _Y)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)) {
  }
  float X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  float Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
};
FLATBUFFERS_STRUCT_END(Float2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float3 FLATBUFFERS_FINAL_CLASS {
 private:
  float X_;
  float Y_;
  float Z_;

 public:
  Float3()
      : X_(0),
        Y_(0),
        Z_(0) {
  }
  Float3(float _X, float _Y, float _Z)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)) {
  }
  float X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  float Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  float Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
};
FLATBUFFERS_STRUCT_END(Float3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float4 FLATBUFFERS_FINAL_CLASS {
 private:
  float X_;
  float Y_;
  float Z_;
  float W_;

 public:
  Float4()
      : X_(0),
        Y_(0),
        Z_(0),
        W_(0) {
  }
  Float4(float _X, float _Y, float _Z, float _W)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)),
        W_(::flatbuffers::EndianScalar(_W)) {
  }
  float X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  float Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  float Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
  float W() const {
    return ::flatbuffers::EndianScalar(W_);
  }
};
FLATBUFFERS_STRUCT_END(Float4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Int2 FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t X_;
  int32_t Y_;

 public:
  Int2()
      : X_(0),
        Y_(0) {
  }
  Int2(int32_t _X, int32_t _Y)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)) {
  }
  int32_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  int32_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
};
FLATBUFFERS_STRUCT_END(Int2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Int3 FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t X_;
  int32_t Y_;
  int32_t Z_;

 public:
  Int3()
      : X_(0),
        Y_(0),
        Z_(0) {
  }
  Int3(int32_t _X, int32_t _Y, int32_t _Z)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)) {
  }
  int32_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  int32_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  int32_t Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
};
FLATBUFFERS_STRUCT_END(Int3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Int4 FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t X_;
  int32_t Y_;
  int32_t Z_;
  int32_t W_;

 public:
  Int4()
      : X_(0),
        Y_(0),
        Z_(0),
        W_(0) {
  }
  Int4(int32_t _X, int32_t _Y, int32_t _Z, int32_t _W)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)),
        W_(::flatbuffers::EndianScalar(_W)) {
  }
  int32_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  int32_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  int32_t Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
  int32_t W() const {
    return ::flatbuffers::EndianScalar(W_);
  }
};
FLATBUFFERS_STRUCT_END(Int4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Uint2 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t X_;
  uint32_t Y_;

 public:
  Uint2()
      : X_(0),
        Y_(0) {
  }
  Uint2(uint32_t _X, uint32_t _Y)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)) {
  }
  uint32_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  uint32_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
};
FLATBUFFERS_STRUCT_END(Uint2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Uint3 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t X_;
  uint32_t Y_;
  uint32_t Z_;

 public:
  Uint3()
      : X_(0),
        Y_(0),
        Z_(0) {
  }
  Uint3(uint32_t _X, uint32_t _Y, uint32_t _Z)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)) {
  }
  uint32_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  uint32_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  uint32_t Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
};
FLATBUFFERS_STRUCT_END(Uint3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Uint4 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t X_;
  uint32_t Y_;
  uint32_t Z_;
  uint32_t W_;

 public:
  Uint4()
      : X_(0),
        Y_(0),
        Z_(0),
        W_(0) {
  }
  Uint4(uint32_t _X, uint32_t _Y, uint32_t _Z, uint32_t _W)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)),
        W_(::flatbuffers::EndianScalar(_W)) {
  }
  uint32_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  uint32_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  uint32_t Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
  uint32_t W() const {
    return ::flatbuffers::EndianScalar(W_);
  }
};
FLATBUFFERS_STRUCT_END(Uint4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Unorm2 FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t X_;
  uint8_t Y_;

 public:
  Unorm2()
      : X_(0),
        Y_(0) {
  }
  Unorm2(uint8_t _X, uint8_t _Y)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)) {
  }
  uint8_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  uint8_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
};
FLATBUFFERS_STRUCT_END(Unorm2, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Unorm3 FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t X_;
  uint8_t Y_;
  uint8_t Z_;

 public:
  Unorm3()
      : X_(0),
        Y_(0),
        Z_(0) {
  }
  Unorm3(uint8_t _X, uint8_t _Y, uint8_t _Z)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)) {
  }
  uint8_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  uint8_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  uint8_t Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
};
FLATBUFFERS_STRUCT_END(Unorm3, 3);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Unorm4 FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t X_;
  uint8_t Y_;
  uint8_t Z_;
  uint8_t W_;

 public:
  Unorm4()
      : X_(0),
        Y_(0),
        Z_(0),
        W_(0) {
  }
  Unorm4(uint8_t _X, uint8_t _Y, uint8_t _Z, uint8_t _W)
      : X_(::flatbuffers::EndianScalar(_X)),
        Y_(::flatbuffers::EndianScalar(_Y)),
        Z_(::flatbuffers::EndianScalar(_Z)),
        W_(::flatbuffers::EndianScalar(_W)) {
  }
  uint8_t X() const {
    return ::flatbuffers::EndianScalar(X_);
  }
  uint8_t Y() const {
    return ::flatbuffers::EndianScalar(Y_);
  }
  uint8_t Z() const {
    return ::flatbuffers::EndianScalar(Z_);
  }
  uint8_t W() const {
    return ::flatbuffers::EndianScalar(W_);
  }
};
FLATBUFFERS_STRUCT_END(Unorm4, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float3x4 FLATBUFFERS_FINAL_CLASS {
 private:
  float M11_;
  float M12_;
  float M13_;
  float M14_;
  float M21_;
  float M22_;
  float M23_;
  float M24_;
  float M31_;
  float M32_;
  float M33_;
  float M34_;

 public:
  Float3x4()
      : M11_(0),
        M12_(0),
        M13_(0),
        M14_(0),
        M21_(0),
        M22_(0),
        M23_(0),
        M24_(0),
        M31_(0),
        M32_(0),
        M33_(0),
        M34_(0) {
  }
  Float3x4(float _M11, float _M12, float _M13, float _M14, float _M21, float _M22, float _M23, float _M24, float _M31, float _M32, float _M33, float _M34)
      : M11_(::flatbuffers::EndianScalar(_M11)),
        M12_(::flatbuffers::EndianScalar(_M12)),
        M13_(::flatbuffers::EndianScalar(_M13)),
        M14_(::flatbuffers::EndianScalar(_M14)),
        M21_(::flatbuffers::EndianScalar(_M21)),
        M22_(::flatbuffers::EndianScalar(_M22)),
        M23_(::flatbuffers::EndianScalar(_M23)),
        M24_(::flatbuffers::EndianScalar(_M24)),
        M31_(::flatbuffers::EndianScalar(_M31)),
        M32_(::flatbuffers::EndianScalar(_M32)),
        M33_(::flatbuffers::EndianScalar(_M33)),
        M34_(::flatbuffers::EndianScalar(_M34)) {
  }
  float M11() const {
    return ::flatbuffers::EndianScalar(M11_);
  }
  float M12() const {
    return ::flatbuffers::EndianScalar(M12_);
  }
  float M13() const {
    return ::flatbuffers::EndianScalar(M13_);
  }
  float M14() const {
    return ::flatbuffers::EndianScalar(M14_);
  }
  float M21() const {
    return ::flatbuffers::EndianScalar(M21_);
  }
  float M22() const {
    return ::flatbuffers::EndianScalar(M22_);
  }
  float M23() const {
    return ::flatbuffers::EndianScalar(M23_);
  }
  float M24() const {
    return ::flatbuffers::EndianScalar(M24_);
  }
  float M31() const {
    return ::flatbuffers::EndianScalar(M31_);
  }
  float M32() const {
    return ::flatbuffers::EndianScalar(M32_);
  }
  float M33() const {
    return ::flatbuffers::EndianScalar(M33_);
  }
  float M34() const {
    return ::flatbuffers::EndianScalar(M34_);
  }
};
FLATBUFFERS_STRUCT_END(Float3x4, 48);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float4x4 FLATBUFFERS_FINAL_CLASS {
 private:
  float M11_;
  float M12_;
  float M13_;
  float M14_;
  float M21_;
  float M22_;
  float M23_;
  float M24_;
  float M31_;
  float M32_;
  float M33_;
  float M34_;
  float M41_;
  float M42_;
  float M43_;
  float M44_;

 public:
  Float4x4()
      : M11_(0),
        M12_(0),
        M13_(0),
        M14_(0),
        M21_(0),
        M22_(0),
        M23_(0),
        M24_(0),
        M31_(0),
        M32_(0),
        M33_(0),
        M34_(0),
        M41_(0),
        M42_(0),
        M43_(0),
        M44_(0) {
  }
  Float4x4(float _M11, float _M12, float _M13, float _M14, float _M21, float _M22, float _M23, float _M24, float _M31, float _M32, float _M33, float _M34, float _M41, float _M42, float _M43, float _M44)
      : M11_(::flatbuffers::EndianScalar(_M11)),
        M12_(::flatbuffers::EndianScalar(_M12)),
        M13_(::flatbuffers::EndianScalar(_M13)),
        M14_(::flatbuffers::EndianScalar(_M14)),
        M21_(::flatbuffers::EndianScalar(_M21)),
        M22_(::flatbuffers::EndianScalar(_M22)),
        M23_(::flatbuffers::EndianScalar(_M23)),
        M24_(::flatbuffers::EndianScalar(_M24)),
        M31_(::flatbuffers::EndianScalar(_M31)),
        M32_(::flatbuffers::EndianScalar(_M32)),
        M33_(::flatbuffers::EndianScalar(_M33)),
        M34_(::flatbuffers::EndianScalar(_M34)),
        M41_(::flatbuffers::EndianScalar(_M41)),
        M42_(::flatbuffers::EndianScalar(_M42)),
        M43_(::flatbuffers::EndianScalar(_M43)),
        M44_(::flatbuffers::EndianScalar(_M44)) {
  }
  float M11() const {
    return ::flatbuffers::EndianScalar(M11_);
  }
  float M12() const {
    return ::flatbuffers::EndianScalar(M12_);
  }
  float M13() const {
    return ::flatbuffers::EndianScalar(M13_);
  }
  float M14() const {
    return ::flatbuffers::EndianScalar(M14_);
  }
  float M21() const {
    return ::flatbuffers::EndianScalar(M21_);
  }
  float M22() const {
    return ::flatbuffers::EndianScalar(M22_);
  }
  float M23() const {
    return ::flatbuffers::EndianScalar(M23_);
  }
  float M24() const {
    return ::flatbuffers::EndianScalar(M24_);
  }
  float M31() const {
    return ::flatbuffers::EndianScalar(M31_);
  }
  float M32() const {
    return ::flatbuffers::EndianScalar(M32_);
  }
  float M33() const {
    return ::flatbuffers::EndianScalar(M33_);
  }
  float M34() const {
    return ::flatbuffers::EndianScalar(M34_);
  }
  float M41() const {
    return ::flatbuffers::EndianScalar(M41_);
  }
  float M42() const {
    return ::flatbuffers::EndianScalar(M42_);
  }
  float M43() const {
    return ::flatbuffers::EndianScalar(M43_);
  }
  float M44() const {
    return ::flatbuffers::EndianScalar(M44_);
  }
};
FLATBUFFERS_STRUCT_END(Float4x4, 64);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) BoundingBox FLATBUFFERS_FINAL_CLASS {
 private:
  asdx::res::Float3 Min_;
  asdx::res::Float3 Max_;

 public:
  BoundingBox()
      : Min_(),
        Max_() {
  }
  BoundingBox(const asdx::res::Float3 &_Min, const asdx::res::Float3 &_Max)
      : Min_(_Min),
        Max_(_Max) {
  }
  const asdx::res::Float3 &Min() const {
    return Min_;
  }
  const asdx::res::Float3 &Max() const {
    return Max_;
  }
};
FLATBUFFERS_STRUCT_END(BoundingBox, 24);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) BoundingSphere FLATBUFFERS_FINAL_CLASS {
 private:
  asdx::res::Float3 Center_;
  float Radius_;

 public:
  BoundingSphere()
      : Center_(),
        Radius_(0) {
  }
  BoundingSphere(const asdx::res::Float3 &_Center, float _Radius)
      : Center_(_Center),
        Radius_(::flatbuffers::EndianScalar(_Radius)) {
  }
  const asdx::res::Float3 &Center() const {
    return Center_;
  }
  float Radius() const {
    return ::flatbuffers::EndianScalar(Radius_);
  }
};
FLATBUFFERS_STRUCT_END(BoundingSphere, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Range FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t Offset_;
  uint32_t Count_;

 public:
  Range()
      : Offset_(0),
        Count_(0) {
  }
  Range(uint32_t _Offset, uint32_t _Count)
      : Offset_(::flatbuffers::EndianScalar(_Offset)),
        Count_(::flatbuffers::EndianScalar(_Count)) {
  }
  uint32_t Offset() const {
    return ::flatbuffers::EndianScalar(Offset_);
  }
  uint32_t Count() const {
    return ::flatbuffers::EndianScalar(Count_);
  }
};
FLATBUFFERS_STRUCT_END(Range, 8);

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_RESTYPES_ASDX_RES_H_
