// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TEXTUREBINARY_ASDX_RES_H_
#define FLATBUFFERS_GENERATED_TEXTUREBINARY_ASDX_RES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace asdx {
namespace res {

struct SubresourceInfo;

struct TextureBinary;
struct TextureBinaryBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) SubresourceInfo FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t Width_;
  uint32_t Height_;
  uint64_t RowPitch_;
  uint64_t SlicePitch_;

 public:
  SubresourceInfo()
      : Width_(0),
        Height_(0),
        RowPitch_(0),
        SlicePitch_(0) {
  }
  SubresourceInfo(uint32_t _Width, uint32_t _Height, uint64_t _RowPitch, uint64_t _SlicePitch)
      : Width_(::flatbuffers::EndianScalar(_Width)),
        Height_(::flatbuffers::EndianScalar(_Height)),
        RowPitch_(::flatbuffers::EndianScalar(_RowPitch)),
        SlicePitch_(::flatbuffers::EndianScalar(_SlicePitch)) {
  }
  uint32_t Width() const {
    return ::flatbuffers::EndianScalar(Width_);
  }
  uint32_t Height() const {
    return ::flatbuffers::EndianScalar(Height_);
  }
  uint64_t RowPitch() const {
    return ::flatbuffers::EndianScalar(RowPitch_);
  }
  uint64_t SlicePitch() const {
    return ::flatbuffers::EndianScalar(SlicePitch_);
  }
};
FLATBUFFERS_STRUCT_END(SubresourceInfo, 24);

struct TextureBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TextureBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_DIMENSION = 6,
    VT_WIDTH = 8,
    VT_HEIGHT = 10,
    VT_DEPTHORARRAYSIZE = 12,
    VT_MIPLEVELS = 14,
    VT_FORMAT = 16,
    VT_SUBRESOURCES = 18,
    VT_TEXELS = 20
  };
  uint32_t Version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  uint32_t Dimension() const {
    return GetField<uint32_t>(VT_DIMENSION, 0);
  }
  uint32_t Width() const {
    return GetField<uint32_t>(VT_WIDTH, 0);
  }
  uint32_t Height() const {
    return GetField<uint32_t>(VT_HEIGHT, 0);
  }
  uint16_t DepthOrArraySize() const {
    return GetField<uint16_t>(VT_DEPTHORARRAYSIZE, 0);
  }
  uint16_t MipLevels() const {
    return GetField<uint16_t>(VT_MIPLEVELS, 0);
  }
  uint32_t Format() const {
    return GetField<uint32_t>(VT_FORMAT, 0);
  }
  const ::flatbuffers::Vector<const asdx::res::SubresourceInfo *> *Subresources() const {
    return GetPointer<const ::flatbuffers::Vector<const asdx::res::SubresourceInfo *> *>(VT_SUBRESOURCES);
  }
  const ::flatbuffers::Vector<uint8_t> *Texels() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_TEXELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<uint32_t>(verifier, VT_DIMENSION, 4) &&
           VerifyField<uint32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyField<uint16_t>(verifier, VT_DEPTHORARRAYSIZE, 2) &&
           VerifyField<uint16_t>(verifier, VT_MIPLEVELS, 2) &&
           VerifyField<uint32_t>(verifier, VT_FORMAT, 4) &&
           VerifyOffset(verifier, VT_SUBRESOURCES) &&
           verifier.VerifyVector(Subresources()) &&
           VerifyOffset(verifier, VT_TEXELS) &&
           verifier.VerifyVector(Texels()) &&
           verifier.EndTable();
  }
};

struct TextureBinaryBuilder {
  typedef TextureBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Version(uint32_t Version) {
    fbb_.AddElement<uint32_t>(TextureBinary::VT_VERSION, Version, 0);
  }
  void add_Dimension(uint32_t Dimension) {
    fbb_.AddElement<uint32_t>(TextureBinary::VT_DIMENSION, Dimension, 0);
  }
  void add_Width(uint32_t Width) {
    fbb_.AddElement<uint32_t>(TextureBinary::VT_WIDTH, Width, 0);
  }
  void add_Height(uint32_t Height) {
    fbb_.AddElement<uint32_t>(TextureBinary::VT_HEIGHT, Height, 0);
  }
  void add_DepthOrArraySize(uint16_t DepthOrArraySize) {
    fbb_.AddElement<uint16_t>(TextureBinary::VT_DEPTHORARRAYSIZE, DepthOrArraySize, 0);
  }
  void add_MipLevels(uint16_t MipLevels) {
    fbb_.AddElement<uint16_t>(TextureBinary::VT_MIPLEVELS, MipLevels, 0);
  }
  void add_Format(uint32_t Format) {
    fbb_.AddElement<uint32_t>(TextureBinary::VT_FORMAT, Format, 0);
  }
  void add_Subresources(::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::SubresourceInfo *>> Subresources) {
    fbb_.AddOffset(TextureBinary::VT_SUBRESOURCES, Subresources);
  }
  void add_Texels(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Texels) {
    fbb_.AddOffset(TextureBinary::VT_TEXELS, Texels);
  }
  explicit TextureBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TextureBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TextureBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TextureBinary> CreateTextureBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    uint32_t Dimension = 0,
    uint32_t Width = 0,
    uint32_t Height = 0,
    uint16_t DepthOrArraySize = 0,
    uint16_t MipLevels = 0,
    uint32_t Format = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const asdx::res::SubresourceInfo *>> Subresources = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Texels = 0) {
  TextureBinaryBuilder builder_(_fbb);
  builder_.add_Texels(Texels);
  builder_.add_Subresources(Subresources);
  builder_.add_Format(Format);
  builder_.add_Height(Height);
  builder_.add_Width(Width);
  builder_.add_Dimension(Dimension);
  builder_.add_Version(Version);
  builder_.add_MipLevels(MipLevels);
  builder_.add_DepthOrArraySize(DepthOrArraySize);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TextureBinary> CreateTextureBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t Version = 0,
    uint32_t Dimension = 0,
    uint32_t Width = 0,
    uint32_t Height = 0,
    uint16_t DepthOrArraySize = 0,
    uint16_t MipLevels = 0,
    uint32_t Format = 0,
    const std::vector<asdx::res::SubresourceInfo> *Subresources = nullptr,
    const std::vector<uint8_t> *Texels = nullptr) {
  auto Subresources__ = Subresources ? _fbb.CreateVectorOfStructs<asdx::res::SubresourceInfo>(*Subresources) : 0;
  auto Texels__ = Texels ? _fbb.CreateVector<uint8_t>(*Texels) : 0;
  return asdx::res::CreateTextureBinary(
      _fbb,
      Version,
      Dimension,
      Width,
      Height,
      DepthOrArraySize,
      MipLevels,
      Format,
      Subresources__,
      Texels__);
}

inline const asdx::res::TextureBinary *GetTextureBinary(const void *buf) {
  return ::flatbuffers::GetRoot<asdx::res::TextureBinary>(buf);
}

inline const asdx::res::TextureBinary *GetSizePrefixedTextureBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<asdx::res::TextureBinary>(buf);
}

inline bool VerifyTextureBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<asdx::res::TextureBinary>(nullptr);
}

inline bool VerifySizePrefixedTextureBinaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<asdx::res::TextureBinary>(nullptr);
}

inline void FinishTextureBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::TextureBinary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTextureBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<asdx::res::TextureBinary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace res
}  // namespace asdx

#endif  // FLATBUFFERS_GENERATED_TEXTUREBINARY_ASDX_RES_H_
