include "../../../res/format/ResTypes.fbs";

namespace asdx.res;

enum MaterialBlendState : ubyte
{
    Opaque,
    AlphaBlend,
    Additive,
    Substract,
    Premultiplied,
    Multiply,
    Screen,
}

enum MaterialDepthState : ubyte
{
    ReadWrite,
    ReadOnly,
    WriteOnly,
    None,
}

enum MaterialRasterizerState : ubyte
{
    CullNone,
    CullBack,
    CullFront,
    Wireframe,
}

table MaterialTexture
{
    Name    : string;
    Path    : string;
}

table MaterialBuffer
{
    Size    : uint;
    Data    : [ubyte];
}

table MaterialBinary
{
    Version         : uint;
    Kind            : uint;
    BlendState      : MaterialBlendState;
    DepthState      : MaterialDepthState;
    RasterizerState : MaterialRasterizerState;
    Buffer          : MaterialBuffer;
    Textures        : [MaterialTexture];
}

root_type MaterialBinary;
