include "../../../res/format/ResTypes.fbs";

namespace asdx.res;

enum BlendState : byte
{
    Opaque,
    AlphaBlend,
    Additive,
    Substract,
    Premultiplied,
    Multiply,
    Screen,
}

enum DepthState : byte
{
    ReadWrite,
    ReadOnly,
    WriteOnly,
    None,
}

enum RasterizerState : byte
{
    CullNone,
    CullBack,
    CullFront,
    Wireframe,
}

struct RenderState
{
    Blend      : BlendState;
    Depth      : DepthState;
    Rasterizer : RasterizerState;
    UserFlags  : ubyte;
}

table MaterialTexture
{
    Name    : string (key);
    Path    : string;
}

table MaterialBuffer
{
    Name    : string (key);
    Data    : [ubyte];
}

table MaterialBinary
{
    Version     : uint;
    PixelShader : string;
    States      : RenderState;
    Buffers     : [MaterialBuffer];
    Textures    : [MaterialTexture];
}

root_type MaterialBinary;
