include "../../../res/format/ResTypes.fbs";

namespace asdx.res;

enum MaterialBlendState : ubyte
{
    Opaque,
    AlphaBlend,
    Additive,
    Substract,
    Premultiplied,
    Multiply,
    Screen,
}

enum MaterialDepthState : ubyte
{
    ReadWrite,
    ReadOnly,
    WriteOnly,
    None,
}

enum MaterialRasterizerState : ubyte
{
    CullNone,
    CullBack,
    CullFront,
    Wireframe,
}

table MaterialTexture
{
    Name    : string (key);
    Path    : string;
}

table MaterialParameter
{
    Name    : string (key);
    Value   : float;
}

table MaterialBinary
{
    Version         : uint;
    Kind            : uint;
    BlendState      : MaterialBlendState;
    DepthState      : MaterialDepthState;
    RasterizerState : MaterialRasterizerState;
    Params          : [MaterialParameter];
    Textures        : [MaterialTexture];
}

root_type MaterialBinary;
