namespace asdx.res;

table MapChip
{
    Width       : uint;
    Height      : uint;
    Format      : uint;
    RowPitch    : uint;
    SlicePitch  : uint;
    Pixels      : [ubyte];
}

table Layer
{
    Name        : string;
    Id          : uint;
    Rows        : uint;
    Columns     : uint;
    Data        : [ushort];
}

table TileSet
{
    Name            : string;
    FirstChipId     : uint;
    Columns         : uint;
    TileCount       : uint;
    TileWidth       : uint;
    TileHeight      : uint;
    Image           : MapChip;
}

table MapChipBinary
{
    Version     : uint;
    Rows        : uint;
    Columns     : uint;
    TileWidth   : uint;
    TileHeight  : uint;
    TileSets    : [TileSet];
    Layers      : [Layer];
}

root_type MapChipBinary;
