namespace asdx.res;

struct Bounds
{
    Left   : float;
    Right  : float;
    Top    : float;
    Bottom : float;
}

struct Glyph
{
    Unicode    : uint (key);
    Advance    : float;
    AtlasBound : Bounds;
    PlaneBound : Bounds;
}

table FontBinary
{
    Version       : uint;
    DistanceRange : float;
    FontSize      : uint;
    TextureWidth  : uint;
    TextureHeight : uint;
    EmSize        : float;
    LineHeight    : float;
    Ascender      : float;
    Descender     : float;
    FlipY         : bool;
    TextureFormat : uint;
    Glyphs        : [Glyph];
    Texels        : [ubyte];
}

root_type FontBinary;
