include "../../../res/format/ResTypes.fbs";

namespace asdx.res;

struct KeyFloat3
{
    Time  : float (key);
    Value : Float3;
}

struct KeyQuaternion
{
    Time  : float (key);
    Value : Float4;
}

table MotionTrack
{
    Name      : string (key);
    Positions : [KeyFloat3];
    Rotations : [KeyQuaternion];
    Scalings  : [KeyFloat3];
}

table MotionClip
{
    Name           : string (key);
    Duration       : float;
    TicksPerSecond : float;
    Tracks         : [MotionTrack];
}

table MotionBinary
{
    Version         : uint;
    RootTransform   : Float4x4;
    Clips           : [MotionClip];
}

root_type MotionBinary;
