namespace asdx.res;

struct Float2
{
    X : float;
    Y : float;
}

struct Float3
{
    X : float;
    Y : float;
    Z : float;
}

struct Float4
{
    X : float;
    Y : float;
    Z : float;
    W : float;
}

struct Uint4
{
    X : uint;
    Y : uint;
    Z : uint;
    W : uint;
}

struct Unorm4
{
    X : ubyte;
    Y : ubyte;
    Z : ubyte;
    W : ubyte;
}

struct Float4x4
{
    e11 : float;
    e12 : float;
    e13 : float;
    e14 : float;

    e21 : float;
    e22 : float;
    e23 : float;
    e24 : float;

    e31 : float;
    e32 : float;
    e33 : float;
    e34 : float;

    e41 : float;
    e42 : float;
    e43 : float;
    e44 : float;
}

table Bone
{
    Name         : string (key);
    OffsetMatrix : Float4x4;
}

table Mesh
{
    Name          : string;
    MaterialTag   : string;
    Positions     : [Float3];
    Normals       : [Float3];
    Tangents      : [Float4];
    Colors        : [Unorm4];
    TexCoords     : [Float2];
    BoneWeights   : [Float4];
    BoneIndices   : [Uint4];
    VertexIndices : [uint];
}

table ModelBinary
{
    Version          : uint;
    Meshes           : [Mesh];
    Bones            : [Bone];
    RootTransform    : Float4x4;
    InvRootTransform : Float4x4;
}

root_type ModelBinary;
