namespace asdx.res;

struct Float2
{
    X : float;
    Y : float;
}

struct Float3
{
    X : float;
    Y : float;
    Z : float;
}

struct Float4
{
    X : float;
    Y : float;
    Z : float;
    W : float;
}

struct Uint4
{
    X : uint;
    Y : uint;
    Z : uint;
    W : uint;
}

struct Unorm4
{
    X : ubyte;
    Y : ubyte;
    Z : ubyte;
    W : ubyte;
}

struct Float4x4
{
    M11 : float;
    M12 : float;
    M13 : float;
    M14 : float;

    M21 : float;
    M22 : float;
    M23 : float;
    M24 : float;

    M31 : float;
    M32 : float;
    M33 : float;
    M34 : float;

    M41 : float;
    M42 : float;
    M43 : float;
    M44 : float;
}

table Bone
{
    Name         : string (key);
    OffsetMatrix : Float4x4;
}

table Mesh
{
    Name          : string;
    MaterialTag   : string;
    Positions     : [Float3];
    Normals       : [Float3];
    Tangents      : [Float4];
    Colors        : [Unorm4];
    TexCoords     : [Float2];
    BoneWeights   : [Float4];
    BoneIndices   : [Uint4];
    VertexIndices : [uint];
}

table ModelBinary
{
    Version          : uint;
    Meshes           : [Mesh];
    Bones            : [Bone];
    RootTransform    : Float4x4;
    InvRootTransform : Float4x4;
}

root_type ModelBinary;
