include "../../../res/format/ResTypes.fbs";

namespace asdx.res;

table Bone
{
    Name            : string (key);
    Parent          : int;
    OffsetMatrix    : Float4x4;
    Children        : [int];
}

table Mesh
{
    Name          : string (key);
    MaterialId    : uint;
    Positions     : [Float3];
    Normals       : [Float3];
    Tangents      : [Float4];
    Colors        : [Unorm4];
    TexCoords     : [Float2];
    BoneWeights   : [Float4];
    BoneIndices   : [Uint4];
    VertexIndices : [uint];
    Bounds        : BoundingSphere;
}

table ModelBinary
{
    Version          : uint;
    Meshes           : [Mesh];
    Materials        : [string];
    Bones            : [Bone];
    Bounds           : BoundingSphere;
    RootTransform    : Float4x4;
    InvRootTransform : Float4x4;
}

root_type ModelBinary;
