include "TextureBinary.fbs";

namespace asdx.res;

struct Bounds
{
    Left   : float;
    Right  : float;
    Top    : float;
    Bottom : float;
}

struct Glyph
{
    Unicode    : uint (key);
    Advance    : float;
    AtlasBound : Bounds;
    PlaneBound : Bounds;
}

table FontBinary
{
    Version       : uint;
    DistanceRange : float;
    FontSize      : uint;
    LineHeight    : float;
    Ascender      : float;
    Descender     : float;
    Glyphs        : [Glyph];
    Texture       : TextureBinary;
}

root_type FontBinary;
