include "../../../res/format/ResTypes.fbs";

namespace asdx.res;

table ModelInstance
{
    Tag         : string (key);
    Path        : string;
    Position    : Float3;
    Scale       : Float3;
    Rotation    : Quaternion;
    UserId      : ulong;
}

table PointLight
{
    Tag         : string (key);
    Position    : Float3;
    Color       : Float3;
    Intensity   : float;
    Radius      : float;
}

table SpotLight
{
    Tag         : string (key);
    Position    : Float3;
    Direction   : Float3;
    Color       : Float3;
    Intensity   : float;
    Radius      : float;
    InnerAngle  : float;
    OuterAngle  : float;
}

table DirectionalLight
{
    Tag         : string (key);
    Direction   : Float3;
    Color       : Float3;
    Intensity   : float;
}

table ImageBasedLight
{
    Tag       : string (key);
    Path      : string;
    Intensity : float;
}

table Pin
{
    Tag      : string (key);
    Position : Float3;
    UserId   : ulong;
}

table Volume
{
    Tab         : string (key);
    Position    : Float3;
    Scale       : Float3;
    Rotation    : Quaternion;
    UserId      : ulong;
}

table LevelBinary
{
    ModelInstances  : [ModelInstance];
    PointLights     : [PointLight];
    SpotLights      : [SpotLight];
    DirLights       : [DirectionalLight];
    IblLights       : [ImageBasedLight];
    Pins            : [Pin];
    Volumes         : [Volume];
}

root_type LevelBinary;
