include "TextureBinary.fbs";

namespace asdx.res;

table Layer
{
    Name        : string;
    Id          : uint;
    Rows        : uint;
    Columns     : uint;
    Data        : [ushort];
}

struct Tile
{
    Id        : ushort (key);
    Collision : bool;
    Event     : uint;
}

table TileSet
{
    Name            : string;
    FirstChipId     : ushort;
    Columns         : uint;
    TileCount       : uint;
    TileWidth       : uint;
    TileHeight      : uint;
    Texture         : TextureBinary;
    Tiles           : [Tile];
}

table MapChipBinary
{
    Version     : uint;
    Rows        : uint;
    Columns     : uint;
    TileWidth   : uint;
    TileHeight  : uint;
    TileSets    : [TileSet];
    Layers      : [Layer];
}

root_type MapChipBinary;
