include "../../../res/format/ResTypes.fbs";

namespace asdx.res;

struct MapTileProp
{
    Flags   : ushort;
    EventId : ushort;
}

struct MapChipFrame
{
    Id       : uint;
    Duration : float;
}

table MapChip
{
    Id      : ushort;
    Frames  : [MapChipFrame];
}

table MapLayer
{
    Name    : string;
    Chips   : [ushort];
}

table MapChipBinary
{
    Version         : uint;
    MapCount        : Uint2;
    ChipCount       : Uint2;
    ChipSize        : Uint2;
    TextureSize     : Uint2;
    TexturePath     : string;
    FirstChipId     : ushort;
    Layers          : [MapLayer];
    TileProps       : [MapTileProp];
    Chips           : [MapChip];
}

root_type MapChipBinary;
