namespace asdx.res;

table MapLayer
{
    Name        : string;
    Id          : uint;
    Rows        : uint;
    Columns     : uint;
    Data        : [ushort];
}

struct MapTileFrame
{
    TileId   : ushort;
    Duration : float;
}

table MapTile
{
    Id        : ushort (key);
    Collision : bool;
    Flags     : ubyte;
    Frames    : [MapTileFrame];
}

table MapObject
{
    Name   : string;
    PosX   : int;
    PosY   : int;
    Width  : int;
    Height : int;
    Event  : int;
}

table MapTileSet
{
    Name            : string;
    FirstChipId     : ushort;
    Columns         : uint;
    TileCount       : uint;
    TileWidth       : uint;
    TileHeight      : uint;
    TextureWidth    : uint;
    TextureHeight   : uint;
    TexturePath     : string;
    Tiles           : [MapTile];
}

table MapChipBinary
{
    Version     : uint;
    Rows        : uint;
    Columns     : uint;
    TileWidth   : uint;
    TileHeight  : uint;
    TileSets    : [MapTileSet];
    Layers      : [MapLayer];
    Objects     : [MapObject];
}

root_type MapChipBinary;
