include "../../../res/format/ResTypes.fbs";

namespace asdx.res;

table Bone
{
    Name            : string;
    Parent          : int;
    BindPose        : Float4x4;
    InverseBindPose : Float4x4;
    Children        : [int];
}

table Mesh
{
    Name          : string;
    MaterialId    : uint;
    Positions     : [Float3];
    Normals       : [Float3];
    Tangents      : [Float4];
    Colors        : [Unorm4];
    TexCoords     : [Float2];
    BoneWeights   : [Float4];
    BoneIndices   : [Uint4];
    VertexIndices : [uint];
    Bounds        : BoundingSphere;
}

table Material
{
    Name            : string;
    BaseColorFactor : Float3;
    Alpha           : float;
    OcclusionFactor : float;
    RoughnessFactor : float;
    MetalnessFactor : float;
    Ior             : float;
    EmissiveFactor  : Float3;
    BaseColorMap    : string;
    NormalMap       : string;
    OrmMap          : string;
    EmissiveMap     : string;
}

table ModelBinary
{
    Version          : uint;
    Meshes           : [Mesh];
    Materials        : [Material];
    Bones            : [Bone];
    Bounds           : BoundingSphere;
    RootTransform    : Float4x4;
    InvRootTransform : Float4x4;
}

root_type ModelBinary;
